spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/personal_assistant
    username: assistant
    password: assistant_password
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    banner: false
