package com.personal.assistant.module.scheduler.service;
import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;import com.personal.assistant.common.exception.*;import com.personal.assistant.module.scheduler.dto.SchedulerJobRequest;import com.personal.assistant.module.scheduler.entity.*;import com.personal.assistant.module.scheduler.job.*;import com.personal.assistant.module.scheduler.mapper.*;import org.quartz.*;import org.springframework.boot.ApplicationArguments;import org.springframework.boot.ApplicationRunner;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.time.*;import java.util.*;import java.util.function.Function;import java.util.stream.Collectors;
@Service public class SchedulerJobService implements ApplicationRunner {private final SchedulerJobMapper jobs;private final SchedulerJobLogMapper logs;private final Scheduler scheduler;private final Map<String,JobHandler> handlers;public SchedulerJobService(SchedulerJobMapper j,SchedulerJobLogMapper l,Scheduler s,List<JobHandler> hs){jobs=j;logs=l;scheduler=s;handlers=hs.stream().collect(Collectors.toMap(JobHandler::type,Function.identity()));}
 public List<SchedulerJob> list(Long uid){return jobs.selectList(new LambdaQueryWrapper<SchedulerJob>().eq(SchedulerJob::getUserId,uid).orderByDesc(SchedulerJob::getCreatedAt));}public List<SchedulerJobLog> listLogs(Long uid,Long jobId){if(jobId!=null)require(uid,jobId);List<Long> ids=list(uid).stream().map(SchedulerJob::getId).toList();if(ids.isEmpty())return List.of();return logs.selectList(new LambdaQueryWrapper<SchedulerJobLog>().in(SchedulerJobLog::getJobId,ids).eq(jobId!=null,SchedulerJobLog::getJobId,jobId).orderByDesc(SchedulerJobLog::getStartedAt).last("limit 200"));}
 @Transactional public Long create(Long uid,SchedulerJobRequest r){validate(r);SchedulerJob x=new SchedulerJob();copy(x,r);x.setUserId(uid);x.setCreatedAt(LocalDateTime.now());x.setUpdatedAt(LocalDateTime.now());jobs.insert(x);sync(x);return x.getId();}
 @Transactional public void update(Long uid,Long id,SchedulerJobRequest r){validate(r);SchedulerJob x=require(uid,id);copy(x,r);x.setUpdatedAt(LocalDateTime.now());jobs.updateById(x);sync(x);}
 @Transactional public void toggle(Long uid,Long id,boolean enabled){SchedulerJob x=require(uid,id);x.setEnabled(enabled);x.setUpdatedAt(LocalDateTime.now());jobs.updateById(x);sync(x);}
 public void execute(Long id){SchedulerJob x=jobs.selectById(id);if(x==null||!Boolean.TRUE.equals(x.getEnabled()))return;SchedulerJobLog log=new SchedulerJobLog();log.setJobId(id);log.setStartedAt(LocalDateTime.now());logs.insert(log);try{JobHandler h=handlers.get(x.getJobType());if(h==null)throw new IllegalStateException("未实现任务处理器: "+x.getJobType());log.setResultMessage(h.execute(x.getConfigJson()));log.setSuccess(true);}catch(Exception e){log.setSuccess(false);log.setResultMessage(e.getMessage());}log.setFinishedAt(LocalDateTime.now());logs.updateById(log);}
 @Override public void run(ApplicationArguments args){jobs.selectList(new LambdaQueryWrapper<SchedulerJob>().eq(SchedulerJob::getEnabled,true)).forEach(this::syncQuietly);}
 private void validate(SchedulerJobRequest r){if(!CronExpression.isValidExpression(r.cronExpression()))throw new BusinessException(ErrorCode.VALIDATION_ERROR,"Cron 表达式不合法");if(!Set.of("REMINDER_SCAN","STOCK_COLLECT","STOCK_FUND_FLOW","GOLD_COLLECT","DATA_BACKUP","AUTO_REPORT","LEARNING_REVIEW","HEALTH_CHECK").contains(r.jobType()))throw new BusinessException(ErrorCode.VALIDATION_ERROR,"任务类型不合法");}
 private void syncQuietly(SchedulerJob x){try{sync(x);}catch(Exception ignored){}}
 private void sync(SchedulerJob x){try{JobKey jk=JobKey.jobKey("business-"+x.getId(),"personal-assistant");TriggerKey tk=TriggerKey.triggerKey("business-"+x.getId(),"personal-assistant");if(scheduler.checkExists(jk))scheduler.deleteJob(jk);if(Boolean.TRUE.equals(x.getEnabled())){JobDetail detail=JobBuilder.newJob(DispatchQuartzJob.class).withIdentity(jk).usingJobData("jobId",x.getId()).storeDurably().build();CronTrigger trigger=TriggerBuilder.newTrigger().withIdentity(tk).forJob(detail).withSchedule(CronScheduleBuilder.cronSchedule(x.getCronExpression()).withMisfireHandlingInstructionDoNothing()).build();scheduler.scheduleJob(detail,trigger);}}catch(SchedulerException e){throw new BusinessException(ErrorCode.BUSINESS_ERROR,"同步 Quartz 任务失败");}}
 private SchedulerJob require(Long uid,Long id){SchedulerJob x=jobs.selectById(id);if(x==null||!uid.equals(x.getUserId()))throw new BusinessException(ErrorCode.NOT_FOUND,"调度任务不存在");return x;}private void copy(SchedulerJob x,SchedulerJobRequest r){x.setJobName(r.jobName());x.setJobType(r.jobType());x.setCronExpression(r.cronExpression());x.setEnabled(!Boolean.FALSE.equals(r.enabled()));x.setConfigJson(r.configJson());}
}