<template>
  <div class="blog-site" :class="{ dark: darkMode }">
    <header class="blog-nav">
      <router-link class="blog-brand" to="/blog"><span>R7</span><b>Rain7</b></router-link>
      <nav><router-link to="/blog">首页</router-link><a href="/blog#articles">文章</a><a href="/dashboard">管理</a><button class="theme-button" @click="toggleTheme">{{ darkMode ? '☀' : '☾' }}</button></nav>
    </header>
    <main><router-view/></main>
    <footer class="blog-footer"><div class="footer-brand"><span>R7</span><div><b>Rain7</b><p>把走过的路，写成可以再次抵达的坐标。</p></div></div><span>Powered by Vue & Markdown · {{new Date().getFullYear()}}</span></footer>
  </div>
</template>
<script setup lang="ts">
import{onMounted,ref}from'vue';const darkMode=ref(false);function toggleTheme(){darkMode.value=!darkMode.value;localStorage.setItem('rain7-theme',darkMode.value?'dark':'light');}onMounted(()=>{darkMode.value=localStorage.getItem('rain7-theme')==='dark'||(!localStorage.getItem('rain7-theme')&&matchMedia('(prefers-color-scheme: dark)').matches);document.title='Rain7';});
</script>
<style scoped>
.blog-site{--bg:#f4f6fb;--surface:rgb(255 255 255 / 88%);--solid:#fff;--ink:#24283a;--muted:#747b90;--line:#e7e9f1;--primary:#7467db;--soft:#eeeaff;--shadow:0 18px 45px rgb(45 43 80 / 10%);min-height:100vh;color:var(--ink);background:var(--bg);font-family:Inter,-apple-system,BlinkMacSystemFont,"Segoe UI","Microsoft YaHei",sans-serif;transition:.25s}.blog-site.dark{--bg:#171922;--surface:rgb(35 37 49 / 90%);--solid:#232531;--ink:#f0f1f7;--muted:#a4a9b8;--line:#343746;--primary:#aaa0f7;--soft:#35314f;--shadow:0 18px 45px rgb(0 0 0 / 25%)}.blog-nav{position:fixed;top:20px;left:50%;z-index:40;display:flex;align-items:center;justify-content:space-between;width:min(1120px,calc(100% - 40px));height:62px;padding:0 18px 0 14px;background:var(--surface);border:1px solid rgb(255 255 255 / 25%);border-radius:22px;box-shadow:0 10px 35px rgb(31 28 64 / 14%);backdrop-filter:blur(20px);transform:translateX(-50%)}.blog-brand{display:flex;gap:10px;align-items:center;color:var(--ink);text-decoration:none}.blog-brand span,.footer-brand>span{display:grid;width:39px;height:39px;color:#fff;font-size:14px;font-weight:900;place-items:center;background:linear-gradient(145deg,#9082ed,#6253d3);border-radius:13px;box-shadow:0 8px 18px rgb(101 86 215 / 28%)}.blog-brand b{font-size:17px;letter-spacing:.04em}.blog-nav nav{display:flex;gap:6px;align-items:center}.blog-nav nav a,.theme-button{padding:9px 12px;color:var(--muted);background:transparent;border:0;border-radius:11px;font-size:13px;font-weight:700;text-decoration:none}.blog-nav nav a:hover,.blog-nav nav a.router-link-exact-active{color:var(--primary);background:var(--soft)}.theme-button{width:36px;padding:8px;cursor:pointer;font-size:18px}.blog-footer{display:flex;align-items:center;justify-content:space-between;max-width:1120px;padding:38px 2px 42px;margin:72px auto 0;color:var(--muted);border-top:1px solid var(--line);font-size:12px}.footer-brand{display:flex;gap:12px;align-items:center}.footer-brand p{margin:4px 0 0}.footer-brand>span{width:38px;height:38px}@media(max-width:680px){.blog-nav{top:10px;width:calc(100% - 20px);height:56px;padding:0 10px;border-radius:18px}.blog-brand span{width:36px;height:36px}.blog-brand b{display:none}.blog-nav nav{gap:1px}.blog-nav nav a{padding:8px}.blog-footer{align-items:flex-start;flex-direction:column;gap:24px;padding:30px 18px 34px;margin-top:48px}.footer-brand p{max-width:250px}}
</style>