package com.personal.assistant.module.knowledge.service;
import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;import com.personal.assistant.common.exception.*;import com.personal.assistant.module.knowledge.dto.*;import com.personal.assistant.module.knowledge.entity.*;import com.personal.assistant.module.knowledge.mapper.*;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import org.springframework.util.StringUtils;import java.time.*;import java.util.*;
@Service public class KnowledgeService{private static final ZoneId SHANGHAI=ZoneId.of("Asia/Shanghai");private static final Set<String>SOURCES=Set.of("MANUAL","LEARNING_RECORD","DEV_LOG","BLOG_POST","QUICK_NOTE");private final KnowledgeEntryMapper entries;private final KnowledgeLinkMapper links;private final JdbcTemplate jdbc;public KnowledgeService(KnowledgeEntryMapper entries,KnowledgeLinkMapper links,JdbcTemplate jdbc){this.entries=entries;this.links=links;this.jdbc=jdbc;}
 public List<KnowledgeEntry>list(Long uid,String keyword,String topic,boolean dueOnly){LambdaQueryWrapper<KnowledgeEntry>q=new LambdaQueryWrapper<KnowledgeEntry>().eq(KnowledgeEntry::getUserId,uid).eq(KnowledgeEntry::getArchived,false).eq(StringUtils.hasText(topic),KnowledgeEntry::getTopic,topic).and(StringUtils.hasText(keyword),x->x.like(KnowledgeEntry::getTitle,keyword).or().like(KnowledgeEntry::getMarkdownContent,keyword).or().like(KnowledgeEntry::getTags,keyword)).le(dueOnly,KnowledgeEntry::getReviewAt,now()).orderByAsc(KnowledgeEntry::getReviewAt).orderByDesc(KnowledgeEntry::getUpdatedAt).last("limit 500");return entries.selectList(q);}
 @Transactional public Long create(Long uid,KnowledgeRequest r){KnowledgeEntry x=new KnowledgeEntry();x.setUserId(uid);x.setSourceType("MANUAL");apply(x,r);x.setReviewCount(0);x.setArchived(false);x.setCreatedAt(now());x.setUpdatedAt(now());entries.insert(x);return x.getId();}@Transactional public void update(Long uid,Long id,KnowledgeRequest r){KnowledgeEntry x=owned(uid,id);apply(x,r);x.setUpdatedAt(now());entries.updateById(x);}
 @Transactional public Long importSource(Long uid,KnowledgeImportRequest r){String type=r.sourceType().toUpperCase();if(!SOURCES.contains(type)||"MANUAL".equals(type))throw validation("来源类型不支持");Source source=source(uid,type,r.sourceId());KnowledgeEntry existing=entries.selectOne(new LambdaQueryWrapper<KnowledgeEntry>().eq(KnowledgeEntry::getUserId,uid).eq(KnowledgeEntry::getSourceType,type).eq(KnowledgeEntry::getSourceId,r.sourceId()));if(existing!=null)return existing.getId();KnowledgeEntry x=new KnowledgeEntry();x.setUserId(uid);x.setSourceType(type);x.setSourceId(r.sourceId());x.setTitle(source.title);x.setMarkdownContent(source.content);x.setProjectName(source.project);x.setTags(StringUtils.hasText(r.tags())?r.tags():source.tags);x.setTopic(r.topic());x.setReviewAt(now().plusDays(1));x.setReviewIntervalDays(1);x.setReviewCount(0);x.setArchived(false);x.setCreatedAt(now());x.setUpdatedAt(now());entries.insert(x);return x.getId();}
 @Transactional public void link(Long uid,Long id,KnowledgeLinkRequest r){owned(uid,id);owned(uid,r.targetEntryId());if(id.equals(r.targetEntryId()))throw validation("不能链接自身");KnowledgeLink x=new KnowledgeLink();x.setUserId(uid);x.setSourceEntryId(id);x.setTargetEntryId(r.targetEntryId());x.setLinkType(StringUtils.hasText(r.linkType())?r.linkType():"RELATED");x.setCreatedAt(now());try{links.insert(x);}catch(Exception ignored){}}
 public List<KnowledgeEntry>backlinks(Long uid,Long id){owned(uid,id);List<Long>ids=links.selectList(new LambdaQueryWrapper<KnowledgeLink>().eq(KnowledgeLink::getUserId,uid).and(q->q.eq(KnowledgeLink::getSourceEntryId,id).or().eq(KnowledgeLink::getTargetEntryId,id))).stream().map(x->id.equals(x.getSourceEntryId())?x.getTargetEntryId():x.getSourceEntryId()).distinct().toList();return ids.isEmpty()?List.of():entries.selectBatchIds(ids).stream().filter(x->uid.equals(x.getUserId())).toList();}
 public List<KnowledgeEntry>similar(Long uid,Long id){KnowledgeEntry x=owned(uid,id);String token=firstToken(StringUtils.hasText(x.getTags())?x.getTags():x.getTopic());if(!StringUtils.hasText(token))return List.of();return entries.selectList(new LambdaQueryWrapper<KnowledgeEntry>().eq(KnowledgeEntry::getUserId,uid).ne(KnowledgeEntry::getId,id).and(q->q.like(KnowledgeEntry::getTags,token).or().like(KnowledgeEntry::getTopic,token)).last("limit 10"));}
 @Transactional public void review(Long uid,Long id,boolean remembered){KnowledgeEntry x=owned(uid,id);int count=Optional.ofNullable(x.getReviewCount()).orElse(0)+1;int interval=remembered?Math.min(180,Math.max(1,Optional.ofNullable(x.getReviewIntervalDays()).orElse(1))*2):1;x.setReviewCount(count);x.setReviewIntervalDays(interval);x.setReviewAt(now().plusDays(interval));x.setUpdatedAt(now());entries.updateById(x);}
 private Source source(Long uid,String type,Long id){String sql=switch(type){case "LEARNING_RECORD"->"select coalesce(p.title,'学习记录') title,r.content content,null project,null tags from learning_record r join learning_plan p on p.id=r.plan_id and p.user_id=r.user_id where r.id=? and r.user_id=?";case "DEV_LOG"->"select title,markdown_content content,project_name project,tags from dev_log where id=? and user_id=?";case "BLOG_POST"->"select title,markdown_content content,null project,tags from blog_post where id=? and user_id=?";case "QUICK_NOTE"->"select substring(content,1,120) title,content,null project,null tags from quick_note where id=? and user_id=?";default->throw validation("来源类型不支持");};List<Source>rows=jdbc.query(sql,(rs,n)->new Source(rs.getString("title"),rs.getString("content"),rs.getString("project"),rs.getString("tags")),id,uid);if(rows.isEmpty())throw new BusinessException(ErrorCode.NOT_FOUND,"来源记录不存在");return rows.get(0);}
 private void apply(KnowledgeEntry x,KnowledgeRequest r){x.setTitle(r.title().trim());x.setMarkdownContent(r.markdownContent());x.setTags(r.tags());x.setProjectName(r.projectName());x.setTopic(r.topic());x.setReviewAt(r.reviewAt()==null?now().plusDays(1):r.reviewAt());x.setReviewIntervalDays(r.reviewIntervalDays()==null?1:Math.max(1,r.reviewIntervalDays()));}private KnowledgeEntry owned(Long uid,Long id){KnowledgeEntry x=entries.selectById(id);if(x==null||!uid.equals(x.getUserId()))throw new BusinessException(ErrorCode.NOT_FOUND,"知识条目不存在");return x;}private String firstToken(String value){return StringUtils.hasText(value)?value.split("[,，# ]")[0]:null;}private LocalDateTime now(){return LocalDateTime.now(SHANGHAI);}private BusinessException validation(String m){return new BusinessException(ErrorCode.VALIDATION_ERROR,m);}private record Source(String title,String content,String project,String tags){}
}
