package com.personal.assistant.module.finance.service;

import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.personal.assistant.common.exception.BusinessException;
import com.personal.assistant.common.exception.ErrorCode;
import com.personal.assistant.module.finance.dto.*;
import com.personal.assistant.module.finance.entity.*;
import com.personal.assistant.module.finance.mapper.*;
import lombok.extern.slf4j.Slf4j;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.util.StringUtils;

import java.math.BigDecimal;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.sql.SQLException;
import java.time.*;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.*;

@Slf4j
@Service
public class FinanceService {
    private static final Set<String> DIRECTIONS=Set.of("INCOME","EXPENSE");
    private final FinanceAccountMapper accounts;private final FinanceCategoryMapper categories;private final FinanceCategoryRuleMapper rules;
    private final FinanceImportBatchMapper batches;private final FinanceRawTransactionMapper rawRows;private final FinanceTransactionMapper transactions;
    private final BillFileParser parser;private final ObjectMapper json=new ObjectMapper();
    public FinanceService(FinanceAccountMapper accounts,FinanceCategoryMapper categories,FinanceCategoryRuleMapper rules,FinanceImportBatchMapper batches,FinanceRawTransactionMapper rawRows,FinanceTransactionMapper transactions,BillFileParser parser){this.accounts=accounts;this.categories=categories;this.rules=rules;this.batches=batches;this.rawRows=rawRows;this.transactions=transactions;this.parser=parser;}

    public List<FinanceAccount> listAccounts(Long uid){return accounts.selectList(new LambdaQueryWrapper<FinanceAccount>().eq(FinanceAccount::getUserId,uid).orderByAsc(FinanceAccount::getAccountName));}
    @Transactional public Long saveAccount(Long uid,Long id,FinanceAccountRequest request){String accountName=request.accountName().trim();Long duplicateCount=accounts.selectCount(new LambdaQueryWrapper<FinanceAccount>().eq(FinanceAccount::getUserId,uid).eq(FinanceAccount::getAccountName,accountName).ne(id!=null,FinanceAccount::getId,id));if(duplicateCount>0)throw new BusinessException(ErrorCode.VALIDATION_ERROR,"账户名称已存在，请换一个名称");FinanceAccount item=id==null?new FinanceAccount():requireAccount(uid,id);item.setUserId(uid);item.setAccountName(accountName);item.setAccountType(request.accountType().trim().toUpperCase());item.setInstitution(StringUtils.hasText(request.institution())?request.institution().trim():null);item.setCurrency(StringUtils.hasText(request.currency())?request.currency().toUpperCase():"CNY");item.setEnabled(!Boolean.FALSE.equals(request.enabled()));item.setUpdatedAt(LocalDateTime.now());try{if(id==null){item.setCreatedAt(LocalDateTime.now());accounts.insert(item);}else accounts.updateById(item);}catch(DataIntegrityViolationException exception){String diagnostic=integrityDiagnostic(exception);log.error("资金账户保存失败: userId={}, accountName={}, accountType={}, diagnostic={}",uid,accountName,item.getAccountType(),diagnostic,exception);throw new BusinessException(ErrorCode.VALIDATION_ERROR,"账户保存失败（"+diagnostic+"），请将该诊断码提供给管理员");}return item.getId();}
    public List<FinanceCategory> listCategories(Long uid){ensureDefaultCategories(uid);return categories.selectList(new LambdaQueryWrapper<FinanceCategory>().eq(FinanceCategory::getUserId,uid).orderByAsc(FinanceCategory::getDirection).orderByAsc(FinanceCategory::getSortOrder));}
    @Transactional public Long saveCategory(Long uid,FinanceCategoryRequest request){String direction=StringUtils.hasText(request.direction())?request.direction().trim().toUpperCase():"EXPENSE";if(!DIRECTIONS.contains(direction))throw new BusinessException(ErrorCode.VALIDATION_ERROR,"分类方向不合法");FinanceCategory item=new FinanceCategory();item.setUserId(uid);item.setCategoryName(request.categoryName().trim());item.setDirection(direction);item.setParentId(request.parentId());item.setSortOrder(request.sortOrder()==null?0:request.sortOrder());item.setEnabled(!Boolean.FALSE.equals(request.enabled()));item.setCreatedAt(LocalDateTime.now());categories.insert(item);return item.getId();}
    @Transactional public Long updateCategory(Long uid,Long id,FinanceCategoryRequest request){FinanceCategory item=requireCategory(uid,id);String direction=StringUtils.hasText(request.direction())?request.direction().trim().toUpperCase():item.getDirection();if(!DIRECTIONS.contains(direction))throw new BusinessException(ErrorCode.VALIDATION_ERROR,"分类方向不合法");item.setCategoryName(request.categoryName().trim());item.setDirection(direction);item.setParentId(request.parentId());item.setSortOrder(request.sortOrder()==null?item.getSortOrder():request.sortOrder());item.setEnabled(!Boolean.FALSE.equals(request.enabled()));categories.updateById(item);return id;}
    public List<FinanceCategoryRule> listRules(Long uid){return rules.selectList(new LambdaQueryWrapper<FinanceCategoryRule>().eq(FinanceCategoryRule::getUserId,uid).orderByDesc(FinanceCategoryRule::getPriority));}
    @Transactional public Long saveRule(Long uid,FinanceRuleRequest request){requireCategory(uid,request.categoryId());FinanceCategoryRule rule=new FinanceCategoryRule();rule.setUserId(uid);rule.setRuleName(request.ruleName());rule.setKeyword(request.keyword());rule.setCategoryId(request.categoryId());rule.setPriority(request.priority()==null?0:request.priority());rule.setEnabled(!Boolean.FALSE.equals(request.enabled()));rule.setCreatedAt(LocalDateTime.now());rules.insert(rule);return rule.getId();}
    @Transactional public Long updateRule(Long uid,Long id,FinanceRuleRequest request){FinanceCategoryRule rule=rules.selectById(id);if(rule==null||!uid.equals(rule.getUserId()))throw new BusinessException(ErrorCode.NOT_FOUND,"规则不存在");requireCategory(uid,request.categoryId());rule.setRuleName(request.ruleName().trim());rule.setKeyword(request.keyword().trim());rule.setCategoryId(request.categoryId());rule.setPriority(request.priority()==null?0:request.priority());rule.setEnabled(!Boolean.FALSE.equals(request.enabled()));rules.updateById(rule);return id;}

    @Transactional
    public FinanceImportPreview preview(Long uid,Long accountId,String platform,String fileName,byte[] bytes){
        requireAccount(uid,accountId);if(bytes.length==0||bytes.length>10*1024*1024)throw new BusinessException(ErrorCode.VALIDATION_ERROR,"账单文件不能为空且不能超过 10MB");
        String fileHash=hash(bytes);FinanceImportBatch duplicate=batches.selectOne(new LambdaQueryWrapper<FinanceImportBatch>().eq(FinanceImportBatch::getUserId,uid).eq(FinanceImportBatch::getAccountId,accountId).eq(FinanceImportBatch::getFileHash,fileHash));if(duplicate!=null)throw new BusinessException(ErrorCode.BUSINESS_ERROR,"该账单文件已导入或正在预览");
        List<Map<String,String>> parsed=parser.parse(fileName,bytes);if(parsed.size()>10000)throw new BusinessException(ErrorCode.VALIDATION_ERROR,"单次最多导入 10000 条流水");
        FinanceImportBatch batch=new FinanceImportBatch();batch.setUserId(uid);batch.setAccountId(accountId);batch.setPlatform(platform.toUpperCase());batch.setFileName(fileName);batch.setFileHash(fileHash);batch.setStatus("PREVIEW");batch.setTotalCount(parsed.size());batch.setDuplicateCount(0);batch.setImportedCount(0);batch.setCreatedAt(LocalDateTime.now());batches.insert(batch);
        List<FinanceCategoryRule> userRules=listRules(uid);List<FinanceRawTransaction> rows=new ArrayList<>();int duplicates=0;int invalid=0;int number=1;
        for(Map<String,String> source:parsed){FinanceRawTransaction row=mapRow(uid,batch.getId(),number++,accountId,source,userRules);if(Boolean.TRUE.equals(row.getDuplicateFlag()))duplicates++;if(StringUtils.hasText(row.getValidationError()))invalid++;rawRows.insert(row);rows.add(row);}
        batch.setDuplicateCount(duplicates);batches.updateById(batch);return new FinanceImportPreview(batch.getId(),rows.size(),duplicates,invalid,rows);
    }

    public FinanceImportPreview batch(Long uid,Long batchId){FinanceImportBatch batch=requireBatch(uid,batchId);List<FinanceRawTransaction> rows=rawRows.selectList(new LambdaQueryWrapper<FinanceRawTransaction>().eq(FinanceRawTransaction::getBatchId,batchId).orderByAsc(FinanceRawTransaction::getRowNumber));return new FinanceImportPreview(batchId,rows.size(),batch.getDuplicateCount(),(int)rows.stream().filter(r->StringUtils.hasText(r.getValidationError())).count(),rows);}
    @Transactional public int confirm(Long uid,Long batchId){FinanceImportBatch batch=requireBatch(uid,batchId);if(!"PREVIEW".equals(batch.getStatus()))throw new BusinessException(ErrorCode.BUSINESS_ERROR,"导入批次不能重复确认");List<FinanceRawTransaction> rows=rawRows.selectList(new LambdaQueryWrapper<FinanceRawTransaction>().eq(FinanceRawTransaction::getBatchId,batchId));if(rows.stream().anyMatch(r->StringUtils.hasText(r.getValidationError())))throw new BusinessException(ErrorCode.VALIDATION_ERROR,"存在无效流水，请修正文件后重新导入");int imported=0;for(FinanceRawTransaction row:rows){if(Boolean.TRUE.equals(row.getDuplicateFlag()))continue;FinanceTransaction tx=new FinanceTransaction();tx.setUserId(uid);tx.setAccountId(batch.getAccountId());tx.setImportBatchId(batchId);tx.setCategoryId(row.getCategoryId());tx.setFingerprint(row.getFingerprint());tx.setPlatformTransactionNo(row.getPlatformTransactionNo());tx.setTransactionTime(row.getTransactionTime());tx.setMerchant(row.getMerchant());tx.setDescription(row.getDescription());tx.setDirection(row.getDirection());tx.setAmount(row.getAmount());tx.setTransactionType(row.getTransactionType());tx.setConfirmed(row.getCategoryId()!=null);tx.setCreatedAt(LocalDateTime.now());tx.setUpdatedAt(LocalDateTime.now());transactions.insert(tx);imported++;}batch.setStatus("CONFIRMED");batch.setImportedCount(imported);batch.setConfirmedAt(LocalDateTime.now());batches.updateById(batch);return imported;}
    public List<FinanceImportBatch> listBatches(Long uid){return batches.selectList(new LambdaQueryWrapper<FinanceImportBatch>().eq(FinanceImportBatch::getUserId,uid).orderByDesc(FinanceImportBatch::getCreatedAt).last("limit 100"));}
    public List<FinanceTransaction> listTransactions(Long uid,String keyword,String direction,YearMonth month){LambdaQueryWrapper<FinanceTransaction> query=new LambdaQueryWrapper<FinanceTransaction>().eq(FinanceTransaction::getUserId,uid).eq(StringUtils.hasText(direction),FinanceTransaction::getDirection,direction).and(StringUtils.hasText(keyword),q->q.like(FinanceTransaction::getMerchant,keyword).or().like(FinanceTransaction::getDescription,keyword));if(month!=null)query.ge(FinanceTransaction::getTransactionTime,month.atDay(1).atStartOfDay()).lt(FinanceTransaction::getTransactionTime,month.plusMonths(1).atDay(1).atStartOfDay());return transactions.selectList(query.orderByDesc(FinanceTransaction::getTransactionTime).last("limit 1000"));}
    @Transactional public void categorize(Long uid,Long transactionId,Long categoryId){FinanceTransaction tx=requireTransaction(uid,transactionId);requireCategory(uid,categoryId);tx.setCategoryId(categoryId);tx.setConfirmed(true);tx.setUpdatedAt(LocalDateTime.now());transactions.updateById(tx);}
    public FinanceMonthlySummary monthly(Long uid,YearMonth month){List<FinanceTransaction> rows=listTransactions(uid,null,null,month);Map<Long,String> names=new HashMap<>();listCategories(uid).forEach(c->names.put(c.getId(),c.getCategoryName()));BigDecimal income=sum(rows,"INCOME");BigDecimal expense=sum(rows,"EXPENSE");Map<String,BigDecimal> grouped=new LinkedHashMap<>();rows.stream().filter(r->"EXPENSE".equals(r.getDirection())).forEach(r->grouped.merge(names.getOrDefault(r.getCategoryId(),"未分类"),r.getAmount(),BigDecimal::add));List<FinanceMonthlySummary.CategoryAmount> categoryAmounts=grouped.entrySet().stream().sorted(Map.Entry.<String,BigDecimal>comparingByValue().reversed()).map(e->new FinanceMonthlySummary.CategoryAmount(e.getKey(),e.getValue())).toList();return new FinanceMonthlySummary(month.toString(),income,expense,income.subtract(expense),categoryAmounts);}

    @Transactional public void ensureDefaultCategories(Long uid){if(categories.selectCount(new LambdaQueryWrapper<FinanceCategory>().eq(FinanceCategory::getUserId,uid))>0)return;String[][] defaults={{"EXPENSE","餐饮"},{"EXPENSE","交通"},{"EXPENSE","购物"},{"EXPENSE","居住"},{"EXPENSE","医疗"},{"EXPENSE","学习"},{"EXPENSE","娱乐"},{"INCOME","工资"},{"INCOME","投资收益"},{"INCOME","其他收入"}};int order=0;for(String[] value:defaults){FinanceCategory item=new FinanceCategory();item.setUserId(uid);item.setDirection(value[0]);item.setCategoryName(value[1]);item.setSortOrder(order++);item.setEnabled(true);item.setCreatedAt(LocalDateTime.now());categories.insert(item);}}
    private FinanceRawTransaction mapRow(Long uid,Long batchId,int number,Long accountId,Map<String,String> source,List<FinanceCategoryRule> userRules){FinanceRawTransaction row=new FinanceRawTransaction();row.setBatchId(batchId);row.setRowNumber(number);try{row.setRawJson(json.writeValueAsString(source));}catch(Exception e){row.setRawJson("{}");}row.setTransactionTime(parseTime(first(source,"交易时间","交易日期","记账日期","入账时间","时间")));row.setPlatformTransactionNo(first(source,"交易号","交易单号","商户订单号","流水号","订单号"));row.setMerchant(first(source,"交易对方","商户名称","商品说明","交易摘要","对方户名"));row.setDescription(first(source,"商品说明","交易摘要","备注","交易类型","用途"));String direction=first(source,"收/支","收支","交易类型","借贷标记","类型");row.setDirection(normalizeDirection(direction,source));row.setAmount(parseAmount(first(source,"金额","金额(元)","交易金额","支出金额","收入金额","交易金额(元)")));row.setTransactionType(normalizeType(direction,row.getDescription()));String validation=validate(row);row.setValidationError(validation);row.setFingerprint(hash((accountId+"|"+nullSafe(row.getPlatformTransactionNo())+"|"+row.getTransactionTime()+"|"+row.getAmount()+"|"+row.getDirection()+"|"+nullSafe(row.getMerchant())).getBytes(StandardCharsets.UTF_8)));row.setDuplicateFlag(transactions.selectCount(new LambdaQueryWrapper<FinanceTransaction>().eq(FinanceTransaction::getUserId,uid).eq(FinanceTransaction::getFingerprint,row.getFingerprint()))>0);String text=(nullSafe(row.getMerchant())+" "+nullSafe(row.getDescription())).toLowerCase();row.setCategoryId(userRules.stream().filter(r->Boolean.TRUE.equals(r.getEnabled())&&text.contains(r.getKeyword().toLowerCase())).map(FinanceCategoryRule::getCategoryId).findFirst().orElse(null));return row;}
    private String first(Map<String,String> source,String...aliases){for(String alias:aliases)for(Map.Entry<String,String> entry:source.entrySet())if(entry.getKey().replace(" ","").contains(alias.replace(" ",""))&&StringUtils.hasText(entry.getValue()))return entry.getValue().trim();return null;}
    private LocalDateTime parseTime(String value){if(!StringUtils.hasText(value))return null;for(DateTimeFormatter f:List.of(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"),DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss"),DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm"),DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm"))){try{return LocalDateTime.parse(value,f);}catch(DateTimeParseException ignored){}}try{return LocalDate.parse(value).atStartOfDay();}catch(Exception ignored){return null;}}
    private BigDecimal parseAmount(String value){if(!StringUtils.hasText(value))return null;try{return new BigDecimal(value.replace(",","").replace("¥","").replace("￥","").replace("元","").trim()).abs();}catch(Exception e){return null;}}
    private String normalizeDirection(String value,Map<String,String> source){String text=nullSafe(value);if(text.contains("收入")||text.equals("收")||StringUtils.hasText(first(source,"收入金额")))return "INCOME";return "EXPENSE";}
    private String normalizeType(String direction,String description){String text=nullSafe(direction)+nullSafe(description);if(text.contains("退款"))return "REFUND";if(text.contains("还款"))return "REPAYMENT";if(text.contains("转账"))return "TRANSFER";return "INCOME".equals(normalizeDirection(direction,Map.of()))?"INCOME":"EXPENSE";}
    private String validate(FinanceRawTransaction row){List<String> errors=new ArrayList<>();if(row.getTransactionTime()==null)errors.add("交易时间无法识别");if(row.getAmount()==null)errors.add("金额无法识别");if(!DIRECTIONS.contains(row.getDirection()))errors.add("收支方向无法识别");return String.join("；",errors);}
    private BigDecimal sum(List<FinanceTransaction> rows,String direction){return rows.stream().filter(r->direction.equals(r.getDirection())).map(FinanceTransaction::getAmount).reduce(BigDecimal.ZERO,BigDecimal::add);}
    private FinanceAccount requireAccount(Long uid,Long id){FinanceAccount item=accounts.selectById(id);if(item==null||!uid.equals(item.getUserId()))throw new BusinessException(ErrorCode.NOT_FOUND,"资金账户不存在");return item;}
    private FinanceCategory requireCategory(Long uid,Long id){FinanceCategory item=categories.selectById(id);if(item==null||!uid.equals(item.getUserId()))throw new BusinessException(ErrorCode.NOT_FOUND,"账单分类不存在");return item;}
    private FinanceImportBatch requireBatch(Long uid,Long id){FinanceImportBatch item=batches.selectById(id);if(item==null||!uid.equals(item.getUserId()))throw new BusinessException(ErrorCode.NOT_FOUND,"导入批次不存在");return item;}
    private FinanceTransaction requireTransaction(Long uid,Long id){FinanceTransaction item=transactions.selectById(id);if(item==null||!uid.equals(item.getUserId()))throw new BusinessException(ErrorCode.NOT_FOUND,"交易不存在");return item;}
    private String hash(byte[] bytes){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(bytes));}catch(Exception e){throw new IllegalStateException(e);}}
    private String nullSafe(String value){return value==null?"":value;}
    static String integrityDiagnostic(Throwable exception){Throwable current=exception;String sqlState=null;String constraint=null;while(current!=null){if(current instanceof SQLException sqlException&&sqlException.getSQLState()!=null)sqlState=sqlException.getSQLState();String message=current.getMessage();if(message!=null){java.util.regex.Matcher matcher=java.util.regex.Pattern.compile("constraint \"([^\"]+)\"").matcher(message);if(matcher.find())constraint=matcher.group(1);}current=current.getCause();}return "SQLState "+(sqlState==null?"unknown":sqlState)+(constraint==null?"":" / "+constraint);}
}
