<template>
  <div class="editor-page">
    <header class="editor-top"><div><el-button text @click="router.push('/blog/manage')">← 返回文章</el-button><span :class="['save-state',saveState]">{{saveText}}</span></div><div><el-button @click="previewPublic">阅读预览</el-button><el-button :loading="saving" @click="save(false)">保存草稿</el-button><el-button type="primary" :loading="saving" @click="save(true)">保存并发布</el-button></div></header>
    <section class="editor-meta">
      <el-input v-model="form.title" class="title-input" placeholder="输入文章标题…" maxlength="200"/>
      <div class="meta-grid"><el-input v-model="form.slug" placeholder="文章路径 slug（不填则自动生成）"/><el-input v-model="form.category" placeholder="分类，如：Java"/><el-input v-model="form.tags" placeholder="标签，逗号分隔"/><el-select v-model="form.site"><el-option label="工作记录博客" value="WORK"/><el-option label="Rain7 独立博客" value="RAIN7"/></el-select><el-switch v-model="form.pinned" active-text="置顶"/></div>
      <el-input v-model="form.summary" type="textarea" :rows="2" maxlength="500" show-word-limit placeholder="文章摘要：让读者快速知道这篇文章解决什么问题"/>
      <div class="cover-row"><el-input v-model="form.coverUrl" placeholder="封面图片 URL，可上传正文图片后复制地址"/><el-upload :show-file-list="false" :http-request="uploadCover" accept="image/jpeg,image/png,image/webp,image/gif"><el-button :loading="uploading">上传封面</el-button></el-upload><el-button @click="advanced=!advanced">{{advanced?'收起':'SEO 设置'}}</el-button></div>
      <div v-if="advanced" class="seo-grid"><el-input v-model="form.seoTitle" placeholder="SEO 标题（可选）"/><el-input v-model="form.seoDescription" placeholder="SEO 描述（可选）"/></div>
    </section>
    <section class="writing-shell"><div class="writing-toolbar"><span>Markdown</span><div><input ref="markdownFileInput" class="markdown-file-input" type="file" accept=".md,.markdown,text/markdown,text/plain" @change="importMarkdown"/><el-button text :loading="importing" @click="markdownFileInput?.click()">导入 MD</el-button><el-upload :show-file-list="false" :http-request="uploadImage" accept="image/jpeg,image/png,image/webp,image/gif"><el-button text :loading="uploading">插入图片</el-button></el-upload><small :class="{overLimit:form.markdownContent.length>CONTENT_LIMIT}" :title="`单篇最多 ${CONTENT_LIMIT.toLocaleString()} 个字符，超限会提示且不会截取`">支持长文 · {{form.markdownContent.length.toLocaleString()}} 字符</small></div></div><div class="writing-grid"><textarea v-model="form.markdownContent" class="markdown-editor" spellcheck="false" placeholder="# 从这里开始写作…&#10;&#10;支持粘贴长文本，或点击“导入 MD”读取 Markdown 文件。" @paste="handleMarkdownPaste"/><div class="preview-pane"><article><MarkdownContent :content="form.markdownContent"/></article></div></div></section>
  </div>
</template>
<script setup lang="ts">
import type{UploadRequestOptions}from'element-plus';import{ElMessage,ElMessageBox}from'element-plus';import{computed,nextTick,onBeforeUnmount,onMounted,reactive,ref,watch}from'vue';import{useRoute,useRouter}from'vue-router';import{createBlogPost,getBlogPost,publishBlogPost,updateBlogPost,uploadBlogAsset,type BlogPostPayload}from'@/api/blog';import MarkdownContent from'@/components/MarkdownContent.vue';
type DraftSnapshot={savedAt:number;data:BlogPostPayload};
type ImportedMarkdown={markdown:string;title:string;summary:string;category:string;tags:string;coverUrl:string};
const CONTENT_LIMIT=500_000;const route=useRoute(),router=useRouter(),saving=ref(false),uploading=ref(false),importing=ref(false),advanced=ref(false),previewVisible=ref(false),postId=ref<number>(),saveState=ref('saved'),ready=ref(false),markdownFileInput=ref<HTMLInputElement>();let timer:number|undefined,draftWarningShown=false;
const blank=():BlogPostPayload=>({title:'',slug:'',summary:'',markdownContent:'# 新文章\n\n从这里开始写作。',coverUrl:'',category:'',tags:'',site:'RAIN7',pinned:false,seoTitle:'',seoDescription:''});const form=reactive(blank());const draftKey=computed(()=>`blog-editor-draft-${postId.value||'new'}`);const saveText=computed(()=>saveState.value==='saving'?'正在保存本地草稿…':saveState.value==='dirty'?'有未保存内容':saveState.value==='error'?'本地草稿保存失败':'本地草稿已保存');
function payload():BlogPostPayload{return{...form};}function persistLocalDraft(key=draftKey.value){saveState.value='saving';try{const snapshot:DraftSnapshot={savedAt:Date.now(),data:payload()};localStorage.setItem(key,JSON.stringify(snapshot));saveState.value='saved';}catch{saveState.value='error';if(!draftWarningShown){draftWarningShown=true;ElMessage.warning('正文较长，本地草稿保存失败；请及时点击“保存草稿”保存到服务器');}}}function scheduleLocalSave(){if(!ready.value)return;saveState.value='dirty';clearTimeout(timer);timer=window.setTimeout(()=>persistLocalDraft(),600);}async function restoreLocal(serverUpdatedAt?:string){try{const value=localStorage.getItem(draftKey.value);if(!value)return;const parsed=JSON.parse(value)as DraftSnapshot|BlogPostPayload;const data='data'in parsed?parsed.data:parsed;const savedAt='savedAt'in parsed?Number(parsed.savedAt):0;if(serverUpdatedAt&&(!savedAt||savedAt<=new Date(serverUpdatedAt).getTime()))return;const confirmed=await ElMessageBox.confirm(`检测到一份本地草稿，正文 ${data.markdownContent.length.toLocaleString()} 个字符。是否恢复？`,'发现本地草稿',{confirmButtonText:'恢复草稿',cancelButtonText:postId.value?'使用服务器内容':'放弃草稿',distinguishCancelAndClose:true,type:'info'}).then(()=>true).catch(action=>{if(action==='cancel')localStorage.removeItem(draftKey.value);return false;});if(!confirmed)return;Object.assign(form,data);ElMessage.success(`已完整恢复本地草稿，共 ${data.markdownContent.length.toLocaleString()} 个字符`);}catch{localStorage.removeItem(draftKey.value);}}
async function ensurePost(data=payload()){if(postId.value)return postId.value;if(!data.title.trim()){ElMessage.warning('请先填写标题');throw new Error('title required');}const previousKey=draftKey.value;postId.value=(await createBlogPost(data)).data;localStorage.removeItem(previousKey);persistLocalDraft();await router.replace(`/blog/manage/${postId.value}`);return postId.value;}
async function save(publish:boolean){if(!form.title.trim()||!form.markdownContent.trim()){ElMessage.warning('请填写标题和正文');return;}if(form.markdownContent.length>CONTENT_LIMIT){ElMessage.error(`正文不能超过 ${CONTENT_LIMIT.toLocaleString()} 个字符，当前内容不会被截取，请精简后再保存`);return;}clearTimeout(timer);persistLocalDraft();saving.value=true;try{const data=payload(),existing=Boolean(postId.value),id=await ensurePost(data);if(existing)await updateBlogPost(id,data);if(publish)await publishBlogPost(id);const stored=(await getBlogPost(id)).data;if(stored.markdownContent!==data.markdownContent){saveState.value='error';ElMessage.error('服务器返回的正文与编辑内容不一致，本地草稿已保留，请勿关闭页面');return;}localStorage.removeItem(draftKey.value);saveState.value='saved';ElMessage.success(publish?'文章已发布':'草稿已完整保存');await router.replace('/blog/manage');}finally{saving.value=false;}}
async function upload(file:File){uploading.value=true;try{const id=await ensurePost();return(await uploadBlogAsset(id,file)).data.url;}finally{uploading.value=false;}}async function uploadImage(options:UploadRequestOptions){const url=await upload(options.file);form.markdownContent+=`\n\n![${options.file.name}](${url})\n`;scheduleLocalSave();}async function uploadCover(options:UploadRequestOptions){form.coverUrl=await upload(options.file);scheduleLocalSave();}
function handleMarkdownPaste(event:ClipboardEvent){const text=event.clipboardData?.getData('text/plain');if(!text)return;const target=event.currentTarget as HTMLTextAreaElement,start=target.selectionStart,end=target.selectionEnd,nextLength=form.markdownContent.length-(end-start)+text.length;event.preventDefault();if(nextLength>CONTENT_LIMIT){ElMessage.error(`本次粘贴后将达到 ${nextLength.toLocaleString()} 个字符，已整段取消，现有正文未被截断`);return;}form.markdownContent=`${form.markdownContent.slice(0,start)}${text}${form.markdownContent.slice(end)}`;void nextTick(()=>{const cursor=start+text.length;target.focus();target.setSelectionRange(cursor,cursor);});if(text.length>=5_000)ElMessage.success(`已完整粘贴 ${text.length.toLocaleString()} 个字符`);}
function decodeMarkdown(buffer:ArrayBuffer){try{return new TextDecoder('utf-8',{fatal:true}).decode(buffer);}catch{try{return new TextDecoder('gb18030').decode(buffer);}catch{return new TextDecoder().decode(buffer);}}}
function cleanMetadataValue(value:string){const trimmed=value.trim();if((trimmed.startsWith('"')&&trimmed.endsWith('"'))||(trimmed.startsWith("'")&&trimmed.endsWith("'")))return trimmed.slice(1,-1);return trimmed;}
function parseMarkdownDocument(source:string,fileName:string):ImportedMarkdown{let markdown=source.replace(/^\uFEFF/,'');const metadata:Record<string,string>={};const frontMatter=markdown.match(/^---[ \t]*\r?\n([\s\S]*?)\r?\n---[ \t]*(?:\r?\n|$)/);if(frontMatter){for(const line of frontMatter[1].split(/\r?\n/)){const match=line.match(/^([a-zA-Z][\w-]*):\s*(.*)$/);if(match)metadata[match[1].toLowerCase()]=cleanMetadataValue(match[2]);}markdown=markdown.slice(frontMatter[0].length);}const heading=markdown.match(/^\s*#\s+(.+?)\s*$/m)?.[1]?.trim();const fileTitle=fileName.replace(/\.(?:md|markdown)$/i,'');const tags=(metadata.tags||'').replace(/^\[|\]$/g,'').split(/[,，]/).map(cleanMetadataValue).filter(Boolean).join(',');return{markdown,title:metadata.title||heading||fileTitle,summary:metadata.summary||metadata.description||'',category:metadata.category||'',tags,coverUrl:metadata.coverurl||metadata['cover-url']||metadata.cover||''};}
async function importMarkdown(event:Event){const input=event.target as HTMLInputElement,file=input.files?.[0];if(!file)return;importing.value=true;try{if(!/\.(?:md|markdown)$/i.test(file.name)){ElMessage.warning('请选择 .md 或 .markdown 文件');return;}const imported=parseMarkdownDocument(decodeMarkdown(await file.arrayBuffer()),file.name);if(!imported.markdown.trim()){ElMessage.warning('Markdown 文件没有可导入的正文');return;}if(imported.markdown.length>CONTENT_LIMIT){ElMessage.error(`文件正文共 ${imported.markdown.length.toLocaleString()} 个字符，超过单篇上限，已取消导入且不会截断`);return;}const current=form.markdownContent.trim(),defaultContent=blank().markdownContent.trim();if(current&&current!==defaultContent){const confirmed=await ElMessageBox.confirm(`导入将替换当前 ${form.markdownContent.length.toLocaleString()} 个字符的正文，是否继续？`,'导入 Markdown',{confirmButtonText:'替换并导入',cancelButtonText:'取消',type:'warning'}).catch(()=>false);if(!confirmed)return;}form.markdownContent=imported.markdown;if(!form.title.trim())form.title=imported.title.slice(0,200);if(!form.summary.trim())form.summary=imported.summary.slice(0,500);if(!form.category.trim())form.category=imported.category.slice(0,100);if(!form.tags.trim())form.tags=imported.tags.slice(0,500);if(!form.coverUrl.trim())form.coverUrl=imported.coverUrl.slice(0,1000);clearTimeout(timer);persistLocalDraft();ElMessage.success(`已完整导入“${file.name}”，正文 ${imported.markdown.length.toLocaleString()} 个字符`);}finally{importing.value=false;input.value='';}}
function previewPublic(){previewVisible.value=true;}
function persistBeforeUnload(){clearTimeout(timer);if(saveState.value==='dirty')persistLocalDraft();}
watch(form,scheduleLocalSave,{deep:true,flush:'sync'});onMounted(async()=>{const id=Number(route.params.id);let updatedAt:string|undefined;if(Number.isFinite(id)){postId.value=id;const post=(await getBlogPost(id)).data;updatedAt=post.updatedAt;Object.assign(form,{title:post.title,slug:post.slug,summary:post.summary||'',markdownContent:post.markdownContent,coverUrl:post.coverUrl||'',category:post.category||'',tags:post.tags||'',site:post.site||'WORK',pinned:post.pinned,seoTitle:post.seoTitle||'',seoDescription:post.seoDescription||''});}await restoreLocal(updatedAt);ready.value=true;window.addEventListener('beforeunload',persistBeforeUnload);});onBeforeUnmount(()=>{window.removeEventListener('beforeunload',persistBeforeUnload);clearTimeout(timer);if(saveState.value==='dirty')persistLocalDraft();});
</script>
<style scoped>.editor-page{display:flex;flex-direction:column;gap:16px;min-height:calc(100vh - 132px)}.editor-top{display:flex;align-items:center;justify-content:space-between;gap:16px;padding:12px 16px;background:rgb(255 255 255 / 92%);border:1px solid #e2e8f0;border-radius:16px;box-shadow:0 12px 28px rgb(15 23 42 / 7%);backdrop-filter:blur(14px)}.editor-top>div{display:flex;align-items:center;gap:10px}.save-state{color:#94a3b8;font-size:12px}.save-state.dirty{color:#d97706}.save-state.error,.writing-toolbar small.overLimit{color:#dc2626}.editor-meta{display:flex;flex-direction:column;gap:14px;padding:22px;background:#fff;border:1px solid #e2e8f0;border-radius:20px}.title-input :deep(input){height:58px;font-size:28px;font-weight:800}.meta-grid{display:grid;grid-template-columns:1.7fr 1fr 1.1fr 1fr auto;gap:12px;align-items:center}.cover-row,.seo-grid{display:grid;grid-template-columns:1fr auto auto;gap:10px}.seo-grid{grid-template-columns:1fr 1fr}.writing-shell{overflow:hidden;background:#fff;border:1px solid #dbe3ee;border-radius:20px;box-shadow:0 18px 45px rgb(15 23 42 / 7%)}.writing-toolbar{display:flex;min-height:48px;align-items:center;justify-content:space-between;gap:12px;padding:6px 18px;color:#64748b;background:#f8fafc;border-bottom:1px solid #e2e8f0;font-size:13px;font-weight:700}.writing-toolbar>div{display:flex;align-items:center;justify-content:flex-end;gap:12px;flex-wrap:wrap}.markdown-file-input{display:none}.writing-grid{display:grid;grid-template-columns:1fr 1fr;min-height:640px}.markdown-editor{width:100%;min-height:640px;padding:28px;resize:vertical;color:#25334a;background:#fbfdff;border:0;border-right:1px solid #e2e8f0;outline:0;font:15px/1.8 "JetBrains Mono",Consolas,monospace}.preview-pane{min-height:640px;padding:30px;overflow:auto}.preview-pane article{max-width:760px;margin:auto}.dialog-preview{max-width:780px;padding:10px;margin:auto}.dialog-preview>h1{color:#14213a;font-family:Georgia,"Songti SC",serif;font-size:38px;line-height:1.35}.dialog-summary{padding-bottom:20px;color:#718096;font-size:16px;line-height:1.8;border-bottom:1px solid #e2e8f0}@media(max-width:900px){.editor-top{align-items:stretch;flex-direction:column}.editor-top>div:last-child{display:grid;grid-template-columns:1fr 1fr 1fr}.meta-grid,.cover-row,.seo-grid{grid-template-columns:1fr}.writing-grid{grid-template-columns:1fr}.markdown-editor{min-height:460px;border-right:0;border-bottom:1px solid #e2e8f0}.preview-pane{min-height:0}.title-input :deep(input){font-size:22px}}@media(max-width:520px){.writing-toolbar{align-items:flex-start;flex-direction:column}.writing-toolbar>div{width:100%;justify-content:flex-start}}</style>
