<template>
  <div class="editor-page">
    <header class="editor-top"><div><el-button text @click="router.push('/blog/manage')">← 返回文章</el-button><span :class="['save-state',saveState]">{{saveText}}</span></div><div><el-button @click="previewPublic">阅读预览</el-button><el-button :loading="saving" @click="save(false)">保存草稿</el-button><el-button type="primary" :loading="saving" @click="save(true)">保存并发布</el-button></div></header>
    <section class="editor-meta">
      <el-input v-model="form.title" class="title-input" placeholder="输入文章标题…" maxlength="200" @input="scheduleLocalSave"/>
      <div class="meta-grid"><el-input v-model="form.slug" placeholder="文章路径 slug（不填则自动生成）"/><el-input v-model="form.category" placeholder="分类，如：Java"/><el-input v-model="form.tags" placeholder="标签，逗号分隔"/><el-switch v-model="form.pinned" active-text="置顶"/></div>
      <el-input v-model="form.summary" type="textarea" :rows="2" maxlength="500" show-word-limit placeholder="文章摘要：让读者快速知道这篇文章解决什么问题"/>
      <div class="cover-row"><el-input v-model="form.coverUrl" placeholder="封面图片 URL，可上传正文图片后复制地址"/><el-upload :show-file-list="false" :http-request="uploadCover" accept="image/jpeg,image/png,image/webp,image/gif"><el-button :loading="uploading">上传封面</el-button></el-upload><el-button @click="advanced=!advanced">{{advanced?'收起':'SEO 设置'}}</el-button></div>
      <div v-if="advanced" class="seo-grid"><el-input v-model="form.seoTitle" placeholder="SEO 标题（可选）"/><el-input v-model="form.seoDescription" placeholder="SEO 描述（可选）"/></div>
    </section>
    <section class="writing-shell"><div class="writing-toolbar"><span>Markdown</span><div><el-upload :show-file-list="false" :http-request="uploadImage" accept="image/jpeg,image/png,image/webp,image/gif"><el-button text :loading="uploading">插入图片</el-button></el-upload><small>{{form.markdownContent.length}} 字符</small></div></div><div class="writing-grid"><textarea v-model="form.markdownContent" class="markdown-editor" spellcheck="false" placeholder="# 从这里开始写作…&#10;&#10;支持 Markdown、代码块、表格、引用和图片。" @input="scheduleLocalSave"/><div class="preview-pane"><article><MarkdownContent :content="form.markdownContent"/></article></div></div></section>
  </div>
</template>
<script setup lang="ts">
import type{UploadRequestOptions}from'element-plus';import{ElMessage}from'element-plus';import{computed,onBeforeUnmount,onMounted,reactive,ref,watch}from'vue';import{useRoute,useRouter}from'vue-router';import{createBlogPost,getBlogPost,publishBlogPost,updateBlogPost,uploadBlogAsset,type BlogPostPayload}from'@/api/blog';import MarkdownContent from'@/components/MarkdownContent.vue';
const route=useRoute(),router=useRouter(),saving=ref(false),uploading=ref(false),advanced=ref(false),previewVisible=ref(false),postId=ref<number>(),saveState=ref('saved');let timer:number|undefined;
const blank=():BlogPostPayload=>({title:'',slug:'',summary:'',markdownContent:'# 新文章\n\n从这里开始写作。',coverUrl:'',category:'',tags:'',pinned:false,seoTitle:'',seoDescription:''});const form=reactive(blank());const draftKey=computed(()=>`blog-editor-draft-${postId.value||'new'}`);const saveText=computed(()=>saveState.value==='saving'?'正在保存本地草稿…':saveState.value==='dirty'?'有未保存内容':'草稿已保存');
function payload(){return{...form};}function scheduleLocalSave(){saveState.value='dirty';clearTimeout(timer);timer=window.setTimeout(()=>{localStorage.setItem(draftKey.value,JSON.stringify(form));saveState.value='saved';},600);}function restoreLocal(){try{const value=localStorage.getItem(draftKey.value);if(value)Object.assign(form,JSON.parse(value));}catch{localStorage.removeItem(draftKey.value);}}
async function ensurePost(){if(postId.value)return postId.value;if(!form.title.trim()){ElMessage.warning('请先填写标题');throw new Error('title required');}postId.value=(await createBlogPost(payload())).data;await router.replace(`/blog/manage/${postId.value}`);return postId.value;}
async function save(publish:boolean){if(!form.title.trim()||!form.markdownContent.trim()){ElMessage.warning('请填写标题和正文');return;}saving.value=true;try{if(postId.value)await updateBlogPost(postId.value,payload());else postId.value=(await createBlogPost(payload())).data;if(publish)await publishBlogPost(postId.value);localStorage.removeItem(draftKey.value);ElMessage.success(publish?'文章已发布':'草稿已保存');await router.replace('/blog/manage');}finally{saving.value=false;}}
async function upload(file:File){uploading.value=true;try{const id=await ensurePost();return(await uploadBlogAsset(id,file)).data.url;}finally{uploading.value=false;}}async function uploadImage(options:UploadRequestOptions){const url=await upload(options.file);form.markdownContent+=`\n\n![${options.file.name}](${url})\n`;scheduleLocalSave();}async function uploadCover(options:UploadRequestOptions){form.coverUrl=await upload(options.file);scheduleLocalSave();}
function previewPublic(){previewVisible.value=true;}
watch(form,scheduleLocalSave,{deep:true});onMounted(async()=>{const id=Number(route.params.id);if(Number.isFinite(id)){postId.value=id;const post=(await getBlogPost(id)).data;Object.assign(form,{title:post.title,slug:post.slug,summary:post.summary||'',markdownContent:post.markdownContent,coverUrl:post.coverUrl||'',category:post.category||'',tags:post.tags||'',pinned:post.pinned,seoTitle:post.seoTitle||'',seoDescription:post.seoDescription||''});}restoreLocal();});onBeforeUnmount(()=>clearTimeout(timer));
</script>
<style scoped>.editor-page{display:flex;flex-direction:column;gap:16px;min-height:calc(100vh - 132px)}.editor-top{position:sticky;top:76px;z-index:5;display:flex;align-items:center;justify-content:space-between;gap:16px;padding:12px 16px;background:rgb(255 255 255 / 92%);border:1px solid #e2e8f0;border-radius:16px;box-shadow:0 12px 28px rgb(15 23 42 / 7%);backdrop-filter:blur(14px)}.editor-top>div{display:flex;align-items:center;gap:10px}.save-state{color:#94a3b8;font-size:12px}.save-state.dirty{color:#d97706}.editor-meta{display:flex;flex-direction:column;gap:14px;padding:22px;background:#fff;border:1px solid #e2e8f0;border-radius:20px}.title-input :deep(input){height:58px;font-size:28px;font-weight:800}.meta-grid{display:grid;grid-template-columns:2fr 1fr 1.3fr auto;gap:12px;align-items:center}.cover-row,.seo-grid{display:grid;grid-template-columns:1fr auto auto;gap:10px}.seo-grid{grid-template-columns:1fr 1fr}.writing-shell{overflow:hidden;background:#fff;border:1px solid #dbe3ee;border-radius:20px;box-shadow:0 18px 45px rgb(15 23 42 / 7%)}.writing-toolbar{display:flex;align-items:center;justify-content:space-between;height:48px;padding:0 18px;color:#64748b;background:#f8fafc;border-bottom:1px solid #e2e8f0;font-size:13px;font-weight:700}.writing-toolbar>div{display:flex;align-items:center;gap:16px}.writing-grid{display:grid;grid-template-columns:1fr 1fr;min-height:640px}.markdown-editor{width:100%;min-height:640px;padding:28px;resize:none;color:#25334a;background:#fbfdff;border:0;border-right:1px solid #e2e8f0;outline:0;font:15px/1.8 "JetBrains Mono",Consolas,monospace}.preview-pane{max-height:75vh;padding:30px;overflow:auto}.preview-pane article{max-width:760px;margin:auto}.dialog-preview{max-width:780px;padding:10px;margin:auto}.dialog-preview>h1{color:#14213a;font-family:Georgia,"Songti SC",serif;font-size:38px;line-height:1.35}.dialog-summary{padding-bottom:20px;color:#718096;font-size:16px;line-height:1.8;border-bottom:1px solid #e2e8f0}@media(max-width:900px){.editor-top{top:60px;align-items:stretch;flex-direction:column}.editor-top>div:last-child{display:grid;grid-template-columns:1fr 1fr 1fr}.meta-grid,.cover-row,.seo-grid{grid-template-columns:1fr}.writing-grid{grid-template-columns:1fr}.markdown-editor{min-height:460px;border-right:0;border-bottom:1px solid #e2e8f0}.preview-pane{max-height:none}.title-input :deep(input){font-size:22px}}</style>
