<template>
  <div class="blog-manage task-page">
    <section class="manage-hero">
      <div><span class="eyebrow">RAIN7 CONTENT STUDIO</span><h2>Rain7 内容管理</h2><p>用 Markdown 写作，把技术、成长与生活发布到 Rain7。</p></div>
      <div class="hero-actions"><el-button @click="openBlog">访问公开博客 ↗</el-button><el-button type="primary" @click="create">写新文章</el-button></div>
    </section>
    <el-card class="filter-card"><el-form :inline="true"><el-form-item label="关键词"><el-input v-model="keyword" clearable placeholder="标题或摘要" @keyup.enter="load"/></el-form-item><el-form-item label="状态"><el-select v-model="status" clearable placeholder="全部" style="width:130px"><el-option label="草稿" value="DRAFT"/><el-option label="已发布" value="PUBLISHED"/></el-select></el-form-item><el-form-item><el-button type="primary" @click="load">查询</el-button></el-form-item></el-form></el-card>
    <el-card><template #header><div class="task-card-header"><span>文章列表</span><small>共 {{ posts.length }} 篇</small></div></template>
      <el-table class="desktop-table" v-loading="loading" :data="posts"><el-table-column prop="title" label="标题" min-width="240"><template #default="{row}"><div class="post-title"><b>{{row.title}}</b><small>/blog/posts/{{row.slug}}</small></div></template></el-table-column><el-table-column prop="category" label="分类" width="110"/><el-table-column label="站点" width="130"><template #default="{row}"><el-tag effect="plain">{{row.site==='RAIN7'?'Rain7':'工作记录'}}</el-tag></template></el-table-column><el-table-column label="状态" width="100"><template #default="{row}"><el-tag :type="row.status==='PUBLISHED'?'success':'info'">{{row.status==='PUBLISHED'?'已发布':'草稿'}}</el-tag></template></el-table-column><el-table-column prop="viewCount" label="阅读" width="80"/><el-table-column label="更新时间" width="180"><template #default="{row}">{{time(row.updatedAt)}}</template></el-table-column><el-table-column label="操作" width="260" fixed="right"><template #default="{row}"><el-button link type="primary" @click="edit(row.id)">编辑</el-button><el-button v-if="row.status==='DRAFT'" link type="success" @click="publish(row)">发布</el-button><el-button v-else link type="warning" @click="unpublish(row)">下线</el-button><el-button v-if="row.status==='PUBLISHED'" link @click="openPost(row.slug)">查看</el-button><el-button link type="danger" @click="remove(row)">删除</el-button></template></el-table-column></el-table>
      <div class="mobile-posts"><article v-for="row in posts" :key="row.id"><div><el-tag size="small" :type="row.status==='PUBLISHED'?'success':'info'">{{row.status==='PUBLISHED'?'已发布':'草稿'}}</el-tag><small>{{row.site==='RAIN7'?'Rain7':'工作记录'}} · {{row.category||'未分类'}}</small></div><h3>{{row.title}}</h3><p>{{row.summary||'还没有填写摘要'}}</p><footer><span>{{time(row.updatedAt)}}</span><el-button text type="primary" @click="edit(row.id)">编辑</el-button></footer></article></div>
      <el-empty v-if="!loading&&!posts.length" description="还没有文章，开始写第一篇吧"/>
    </el-card>
  </div>
</template>
<script setup lang="ts">
import{ElMessage,ElMessageBox}from'element-plus';import{onMounted,ref}from'vue';import{useRouter}from'vue-router';import{deleteBlogPost,listBlogPosts,publishBlogPost,unpublishBlogPost,type BlogPost}from'@/api/blog';
const router=useRouter(),posts=ref<BlogPost[]>([]),loading=ref(false),keyword=ref(''),status=ref('');
async function load(){loading.value=true;try{posts.value=(await listBlogPosts({keyword:keyword.value||undefined,status:status.value||undefined})).data;}finally{loading.value=false;}}
const create=()=>router.push('/blog/manage/new');const edit=(id:number)=>router.push(`/blog/manage/${id}`);const openBlog=()=>window.open('/rain7/','_blank','noopener');const openPost=(slug:string)=>{const row=posts.value.find(item=>item.slug===slug);window.open(row?.site==='RAIN7'?`/rain7/article?slug=${encodeURIComponent(slug)}`:`/blog/posts/${slug}`,'_blank','noopener');};const time=(v:string)=>new Date(v).toLocaleString('zh-CN',{hour12:false});
async function publish(row:BlogPost){await publishBlogPost(row.id);ElMessage.success('文章已发布');await load();}async function unpublish(row:BlogPost){await ElMessageBox.confirm(`确认下线“${row.title}”？公开页面将无法访问。`,'下线确认',{type:'warning'});await unpublishBlogPost(row.id);await load();}async function remove(row:BlogPost){await ElMessageBox.confirm(`永久删除“${row.title}”及其图片？`,'删除确认',{type:'warning'});await deleteBlogPost(row.id);ElMessage.success('文章已删除');await load();}onMounted(load);
</script>
<style scoped>.manage-hero{display:flex;align-items:center;justify-content:space-between;gap:20px;padding:28px 32px;color:#eff6ff;background:radial-gradient(circle at 85% 0,rgb(255 255 255 / 18%),transparent 34%),linear-gradient(135deg,#39315f,#7064ab 58%,#9c92c7);border-radius:24px;box-shadow:0 24px 60px rgb(78 64 139 / 24%)}.eyebrow{color:#ded8ff;font-size:11px;font-weight:800;letter-spacing:.18em}.manage-hero h2{margin:8px 0 6px;font-size:28px}.manage-hero p{margin:0;color:#e3dff7}.hero-actions{display:flex;gap:10px;flex-shrink:0}.post-title{display:flex;flex-direction:column;gap:5px}.post-title small{color:#94a3b8}.task-card-header small{color:#94a3b8}.mobile-posts{display:none}@media(max-width:768px){.manage-hero{align-items:flex-start;flex-direction:column;padding:24px 20px}.hero-actions{width:100%}.hero-actions .el-button{flex:1}.desktop-table{display:none}.mobile-posts{display:grid;gap:12px}.mobile-posts article{padding:16px;border:1px solid #e2e8f0;border-radius:16px;background:#fff}.mobile-posts article>div,.mobile-posts footer{display:flex;align-items:center;justify-content:space-between;gap:8px}.mobile-posts h3{margin:12px 0 6px}.mobile-posts p{color:#64748b}.mobile-posts footer{color:#94a3b8;font-size:12px}}</style>
