package com.personal.assistant.module.learning.service;
import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;import com.personal.assistant.common.exception.*;import com.personal.assistant.module.learning.dto.*;import com.personal.assistant.module.learning.entity.*;import com.personal.assistant.module.learning.mapper.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import org.springframework.util.StringUtils;import java.time.*;import java.util.*;import java.util.stream.Collectors;
@Service public class LearningService {
 private static final Set<String> PLAN_STATUSES=Set.of("NOT_STARTED","IN_PROGRESS","COMPLETED");private static final Set<String> SUMMARY_TYPES=Set.of("WEEKLY","MONTHLY","STAGE");
 private final LearningPlanMapper plans;private final LearningRecordMapper records;private final LearningSummaryMapper summaries;public LearningService(LearningPlanMapper p,LearningRecordMapper r,LearningSummaryMapper s){plans=p;records=r;summaries=s;}
 public List<LearningPlan> listPlans(Long uid,String keyword,String topic,String status){return plans.selectList(new LambdaQueryWrapper<LearningPlan>().eq(LearningPlan::getUserId,uid).eq(LearningPlan::getArchived,false).like(StringUtils.hasText(keyword),LearningPlan::getTitle,keyword).eq(StringUtils.hasText(topic),LearningPlan::getTopic,topic).eq(StringUtils.hasText(status),LearningPlan::getStatus,status).orderByAsc(LearningPlan::getTargetDate).orderByDesc(LearningPlan::getCreatedAt));}
 public LearningPlan getPlan(Long uid,Long id){return requirePlan(uid,id);}
 @Transactional public Long createPlan(Long uid,LearningPlanRequest r){validatePlan(r);LearningPlan p=new LearningPlan();copy(p,r);p.setUserId(uid);p.setArchived(false);p.setCreatedAt(LocalDateTime.now());p.setUpdatedAt(LocalDateTime.now());plans.insert(p);return p.getId();}
 @Transactional public void updatePlan(Long uid,Long id,LearningPlanRequest r){validatePlan(r);LearningPlan p=requirePlan(uid,id);copy(p,r);p.setUpdatedAt(LocalDateTime.now());plans.updateById(p);}
 @Transactional public void archivePlan(Long uid,Long id){LearningPlan p=requirePlan(uid,id);p.setArchived(true);p.setStatus("ARCHIVED");p.setUpdatedAt(LocalDateTime.now());plans.updateById(p);}
 public List<LearningRecord> listRecords(Long uid,Long planId,String keyword){return records.selectList(new LambdaQueryWrapper<LearningRecord>().eq(LearningRecord::getUserId,uid).eq(planId!=null,LearningRecord::getPlanId,planId).like(StringUtils.hasText(keyword),LearningRecord::getContent,keyword).orderByDesc(LearningRecord::getRecordTime));}
 @Transactional public Long createRecord(Long uid,LearningRecordRequest r){requirePlan(uid,r.planId());LearningRecord x=new LearningRecord();x.setUserId(uid);x.setPlanId(r.planId());x.setContent(r.content());x.setDurationMinutes(r.durationMinutes());x.setResult(r.result());x.setProblem(r.problem());x.setNextAction(r.nextAction());x.setRecordTime(r.recordTime());x.setCreatedAt(LocalDateTime.now());records.insert(x);return x.getId();}
 public List<LearningSummary> listSummaries(Long uid,Long planId,String type){return summaries.selectList(new LambdaQueryWrapper<LearningSummary>().eq(LearningSummary::getUserId,uid).eq(planId!=null,LearningSummary::getPlanId,planId).eq(StringUtils.hasText(type),LearningSummary::getSummaryType,type).orderByDesc(LearningSummary::getPeriodEnd));}
 @Transactional public Long createSummary(Long uid,LearningSummaryRequest r){if(r.planId()!=null)requirePlan(uid,r.planId());if(!SUMMARY_TYPES.contains(r.summaryType()))throw new BusinessException(ErrorCode.VALIDATION_ERROR,"总结类型不合法");if(r.periodEnd().isBefore(r.periodStart()))throw new BusinessException(ErrorCode.VALIDATION_ERROR,"周期结束时间不能早于开始时间");LearningSummary x=new LearningSummary();x.setUserId(uid);x.setPlanId(r.planId());x.setSummaryType(r.summaryType());x.setPeriodStart(r.periodStart());x.setPeriodEnd(r.periodEnd());x.setGains(r.gains());x.setProblems(r.problems());x.setImprovements(r.improvements());x.setMarkdownContent(r.markdownContent());x.setTags(r.tags());x.setCreatedAt(LocalDateTime.now());x.setUpdatedAt(LocalDateTime.now());summaries.insert(x);return x.getId();}
 public GrowthStats stats(Long uid){List<LearningPlan> ps=listPlans(uid,null,null,null);List<LearningRecord> rs=listRecords(uid,null,null);List<LearningSummary> ss=listSummaries(uid,null,null);long minutes=rs.stream().mapToLong(x->Optional.ofNullable(x.getDurationMinutes()).orElse(0)).sum();Map<String,Long> topics=ps.stream().collect(Collectors.groupingBy(LearningPlan::getTopic,LinkedHashMap::new,Collectors.counting()));return new GrowthStats(ps.size(),ps.stream().filter(x->"IN_PROGRESS".equals(x.getStatus())).count(),ps.stream().filter(x->"COMPLETED".equals(x.getStatus())).count(),minutes,topics,rs.stream().limit(5).toList(),ss.stream().limit(5).toList());}
 private LearningPlan requirePlan(Long uid,Long id){LearningPlan p=plans.selectById(id);if(p==null||!uid.equals(p.getUserId())||Boolean.TRUE.equals(p.getArchived()))throw new BusinessException(ErrorCode.NOT_FOUND,"学习计划不存在");return p;}
 private void validatePlan(LearningPlanRequest r){if(!PLAN_STATUSES.contains(r.status()))throw new BusinessException(ErrorCode.VALIDATION_ERROR,"计划状态不合法");if(r.startDate()!=null&&r.targetDate()!=null&&r.targetDate().isBefore(r.startDate()))throw new BusinessException(ErrorCode.VALIDATION_ERROR,"目标日期不能早于开始日期");}
 private void copy(LearningPlan p,LearningPlanRequest r){p.setTitle(r.title());p.setTopic(r.topic());p.setTarget(r.target());p.setStage(r.stage());p.setStartDate(r.startDate());p.setTargetDate(r.targetDate());p.setProgress(r.progress());p.setStatus(r.status());p.setResourceLinks(r.resourceLinks());p.setReviewTime(r.reviewTime());}
}