<template><div class="dashboard-grid">
<el-card class="summary-card"><template #header>系统健康</template><div class="health-row"><el-tag :type="health?.status==='UP'?'success':'info'">{{health?.status||'未检查'}}</el-tag><el-button size="small" @click="loadHealth">检查后端</el-button></div><div class="card-text">服务：{{health?.serviceName||'-'}}</div><div class="card-text">版本：{{health?.version||'-'}}</div></el-card>
<el-card class="summary-card"><template #header>今日生活待办</template><el-empty v-if="!lifeTasks.length" description="今天暂无生活事项" :image-size="54"/><div v-for="item in lifeTasks" :key="item.id" class="dashboard-task"><span>{{item.title}}</span><el-tag size="small">{{item.category}}</el-tag></div></el-card>
<el-card class="summary-card"><template #header>进行中的工作重点</template><el-empty v-if="!workTasks.length" description="暂无进行中工作" :image-size="54"/><div v-for="item in workTasks" :key="item.id" class="dashboard-task"><span>{{item.title}}</span><el-tag size="small" type="warning">{{item.projectName||item.workType}}</el-tag></div></el-card>
<el-card class="summary-card quick-note-card"><template #header><div class="health-row"><span>待整理记录</span><el-button size="small" @click="loadQuickNotes">刷新</el-button></div></template><el-empty v-if="!quickNotes.length" description="暂无待整理记录" :image-size="54"/><div v-else class="quick-note-list"><div v-for="note in quickNotes" :key="note.id" class="quick-note-item"><div><div class="quick-note-content">{{note.content}}</div><div class="quick-note-time">{{formatTime(note.createdAt)}}</div></div><el-button text type="primary" @click="archive(note.id)">归档</el-button></div></div></el-card>
<el-card class="summary-card"><template #header>学习成长</template><div class="growth-summary"><b>{{growth?.totalMinutes||0}}</b><span>累计学习分钟</span></div><div class="card-text">进行中计划：{{growth?.inProgressCount||0}}　已完成：{{growth?.completedCount||0}}</div></el-card>
<el-card class="summary-card"><template #header>股票关注</template><div class="growth-summary"><b>{{stockItems.length}}</b><span>个启用关注项</span></div><div class="card-text">{{stockItems.slice(0,4).map(x=>x.stockName).join('、')||'暂无关注股票'}}</div></el-card>
</div></template>
<script setup lang="ts">
import {ElMessage} from 'element-plus';import {onMounted,ref} from 'vue';import {getSystemHealth,type HealthStatusResponse} from '@/api/system';import {archiveQuickNote,listPendingQuickNotes,type QuickNote} from '@/api/quickNote';import {listTasks,type TaskItem} from '@/api/task';import {getGrowthStats,type GrowthStats} from '@/api/learning';import {listWatchItems,type WatchItem} from '@/api/stock';
const health=ref<HealthStatusResponse|null>(null);const quickNotes=ref<QuickNote[]>([]);const lifeTasks=ref<TaskItem[]>([]);const workTasks=ref<TaskItem[]>([]);const growth=ref<GrowthStats>();const stockItems=ref<WatchItem[]>([]);
async function loadStocks(){stockItems.value=(await listWatchItems({enabled:true})).data;}async function loadHealth(){health.value=(await getSystemHealth()).data;}async function loadGrowth(){growth.value=(await getGrowthStats()).data;}async function loadQuickNotes(){quickNotes.value=(await listPendingQuickNotes()).data;}async function loadTasks(){const start=new Date();start.setHours(0,0,0,0);const end=new Date();end.setHours(23,59,59,999);lifeTasks.value=(await listTasks({type:'LIFE',start:start.toISOString().slice(0,19),end:end.toISOString().slice(0,19)})).data;workTasks.value=(await listTasks({type:'WORK',status:'IN_PROGRESS'})).data.slice(0,5);}async function archive(id:number){await archiveQuickNote(id);quickNotes.value=quickNotes.value.filter(n=>n.id!==id);ElMessage.success('记录已归档');}function formatTime(v:string){return new Date(v).toLocaleString('zh-CN');}onMounted(()=>{void loadHealth();void loadQuickNotes();void loadTasks();void loadGrowth();void loadStocks();});
</script>