package com.personal.assistant.module.reminder.service;
import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;import com.personal.assistant.common.exception.*;import com.personal.assistant.module.reminder.dto.*;import com.personal.assistant.module.reminder.entity.*;import com.personal.assistant.module.reminder.mapper.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.time.*;import java.util.*;
@Service public class ReminderService {private static final Set<String> SOURCE_TYPES=Set.of("LIFE","WORK","LEARNING","STOCK","CUSTOM");private final ReminderMapper reminders;private final NotificationChannelMapper channels;private final NotificationLogMapper logs;private final SecretCryptoService crypto;private final NotificationService notification;public ReminderService(ReminderMapper r,NotificationChannelMapper c,NotificationLogMapper l,SecretCryptoService x,NotificationService n){reminders=r;channels=c;logs=l;crypto=x;notification=n;}
 public List<Reminder> list(Long uid,String status){return reminders.selectList(new LambdaQueryWrapper<Reminder>().eq(Reminder::getUserId,uid).eq(status!=null&& !status.isBlank(),Reminder::getStatus,status).orderByAsc(Reminder::getRemindTime));}
 @Transactional public Long create(Long uid,ReminderRequest r){validate(r);Reminder x=new Reminder();copy(x,r);x.setUserId(uid);x.setStatus("PENDING");x.setCreatedAt(LocalDateTime.now());x.setUpdatedAt(LocalDateTime.now());reminders.insert(x);return x.getId();}
 @Transactional public void update(Long uid,Long id,ReminderRequest r){validate(r);Reminder x=requireReminder(uid,id);if(!"PENDING".equals(x.getStatus()))throw new BusinessException(ErrorCode.BUSINESS_ERROR,"只有待触发提醒可以编辑");copy(x,r);x.setUpdatedAt(LocalDateTime.now());reminders.updateById(x);}
 @Transactional public void status(Long uid,Long id,String status){if(!Set.of("COMPLETED","CANCELLED").contains(status))throw new BusinessException(ErrorCode.VALIDATION_ERROR,"提醒状态不合法");Reminder x=requireReminder(uid,id);x.setStatus(status);x.setUpdatedAt(LocalDateTime.now());reminders.updateById(x);}
 public List<ChannelResponse> listChannels(Long uid){return channels.selectList(new LambdaQueryWrapper<NotificationChannel>().eq(NotificationChannel::getUserId,uid).orderByDesc(NotificationChannel::getCreatedAt)).stream().map(x->new ChannelResponse(x.getId(),x.getName(),x.getChannelType(),mask(crypto.decrypt(x.getWebhookEncrypted())),Boolean.TRUE.equals(x.getEnabled()))).toList();}
 @Transactional public Long saveChannel(Long uid,Long id,ChannelRequest r){if(!"WEBHOOK".equals(r.channelType()))throw new BusinessException(ErrorCode.VALIDATION_ERROR,"当前仅支持 WEBHOOK 通道");NotificationChannel x=id==null?new NotificationChannel():requireChannel(uid,id);x.setUserId(uid);x.setName(r.name());x.setChannelType(r.channelType());x.setWebhookEncrypted(crypto.encrypt(r.webhook()));x.setEnabled(!Boolean.FALSE.equals(r.enabled()));x.setUpdatedAt(LocalDateTime.now());if(id==null){x.setCreatedAt(LocalDateTime.now());channels.insert(x);}else channels.updateById(x);return x.getId();}
 public void testChannel(Long uid,Long id){NotificationChannel c=requireChannel(uid,id);notification.send(uid,null,c.getId(),"个人辅助系统测试消息","通知通道配置成功");}
 public List<NotificationLog> listLogs(Long uid){return logs.selectList(new LambdaQueryWrapper<NotificationLog>().eq(NotificationLog::getUserId,uid).orderByDesc(NotificationLog::getCreatedAt).last("limit 100"));}
 @Transactional public int scanDue(){List<Reminder> due=reminders.selectList(new LambdaQueryWrapper<Reminder>().eq(Reminder::getStatus,"PENDING").le(Reminder::getRemindTime,LocalDateTime.now()));int count=0;for(Reminder x:due){try{if(x.getChannelId()==null)throw new BusinessException(ErrorCode.BUSINESS_ERROR,"未配置通知通道");notification.send(x.getUserId(),x.getId(),x.getChannelId(),x.getTitle(),x.getContent());x.setStatus("SENT");x.setSentAt(LocalDateTime.now());x.setLastError(null);}catch(Exception e){x.setStatus("FAILED");x.setLastError(e.getMessage());}x.setUpdatedAt(LocalDateTime.now());reminders.updateById(x);count++;}return count;}
 private void validate(ReminderRequest r){if(!SOURCE_TYPES.contains(r.sourceType()))throw new BusinessException(ErrorCode.VALIDATION_ERROR,"提醒来源类型不合法");}
 private Reminder requireReminder(Long uid,Long id){Reminder x=reminders.selectById(id);if(x==null||!uid.equals(x.getUserId()))throw new BusinessException(ErrorCode.NOT_FOUND,"提醒不存在");return x;}private NotificationChannel requireChannel(Long uid,Long id){NotificationChannel x=channels.selectById(id);if(x==null||!uid.equals(x.getUserId()))throw new BusinessException(ErrorCode.NOT_FOUND,"通知通道不存在");return x;}private void copy(Reminder x,ReminderRequest r){x.setSourceType(r.sourceType());x.setSourceId(r.sourceId());x.setChannelId(r.channelId());x.setTitle(r.title());x.setContent(r.content());x.setRemindTime(r.remindTime());}private String mask(String s){if(s.length()<12)return "******";return s.substring(0,8)+"******"+s.substring(s.length()-4);}
}