import { useEffect, useMemo, useState } from "react";
import { Archive, CalendarDays, Eye, FolderOpen, Search, Tag, UserRound } from "lucide-react";
type Summary={id:number;title:string;slug:string;summary:string|null;coverUrl:string|null;category:string|null;tags:string|null;pinned:boolean;viewCount:number;publishedAt:string};type BlogArchive={posts:Summary[];categories:string[];tags:string[]};
const request=(path:string)=>fetch(path).then(async response=>{const type=response.headers.get("content-type")||"";if(!type.includes("application/json"))throw new Error("文章服务暂时不可用");const body=await response.json();if(!response.ok||(body.code&&body.code!=="SUCCESS"))throw new Error(body.message||"请求失败");return body.data});
const splitTags=(value:string|null)=>value?.split(",").map(item=>item.trim()).filter(Boolean)||[];const readingTime=(post:Summary)=>Math.max(1,Math.ceil(((post.summary?.length||0)+600)/300));
export default function Rain7BlogApp(){const[data,setData]=useState<BlogArchive>({posts:[],categories:[],tags:[]});const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[keyword,setKeyword]=useState("");const[category,setCategory]=useState("");const[tag,setTag]=useState("");const query=useMemo(()=>{const params=new URLSearchParams({site:"RAIN7"});if(keyword)params.set("keyword",keyword);if(category)params.set("category",category);if(tag)params.set("tag",tag);return params.toString()},[keyword,category,tag]);useEffect(()=>{setLoading(true);setError("");request(`/api/public/blog/posts?${query}`).then(setData).catch(error=>setError(error.message)).finally(()=>setLoading(false))},[query]);const clearFilters=()=>{setKeyword("");setCategory("");setTag("")};
return <div className="ryu-home"><div className="ryu-content-grid"><aside className="ryu-sidebar">
<section className="ryu-profile-card"><img src="/rain7/profile.png" alt="Rain7"/><h2>Rain7</h2><i></i><p>欲买桂花同载酒，终不似，少年游！</p><div className="ryu-socials"><a href="/blog/manage" title="内容管理"><UserRound/></a><a href="#rain-categories" title="分类"><FolderOpen/></a><a href="#rain-tags" title="标签"><Tag/></a></div><div className="ryu-stats"><span><Eye/><small>总阅读</small><b>{data.posts.reduce((sum,post)=>sum+(post.viewCount||0),0)}</b></span><span><UserRound/><small>文章数</small><b>{data.posts.length}</b></span></div></section>
<section className="ryu-side-card" id="rain-categories"><h3>分类</h3><button className={!category?"active":""} onClick={()=>setCategory("")}>全部文章 <b>{data.posts.length}</b></button>{data.categories.map(item=><button className={category===item?"active":""} onClick={()=>setCategory(item)} key={item}>{item}<b>›</b></button>)}</section>
<section className="ryu-side-card" id="rain-tags"><h3>标签</h3><div>{data.tags.map(item=><button className={tag===item?"active":""} onClick={()=>setTag(tag===item?"":item)} key={item}>#{item}</button>)}</div></section></aside>
<main className="ryu-post-column"><section className="ryu-feature-grid"><button onClick={clearFilters}><Archive/><span><b>文章归档</b><small>按日期浏览全部文章</small></span></button><button onClick={()=>document.getElementById("rain-categories")?.scrollIntoView({behavior:"smooth"})}><FolderOpen/><span><b>分类</b><small>探索博客中的所有分类</small></span></button><button onClick={()=>document.getElementById("rain-tags")?.scrollIntoView({behavior:"smooth"})}><Tag/><span><b>标签</b><small>按主题发现感兴趣的内容</small></span></button><button onClick={()=>document.getElementById("rain-search")?.focus()}><Search/><span><b>搜索</b><small>搜索博客中的所有文章</small></span></button></section>
<label className="ryu-search"><Search/><input id="rain-search" value={keyword} onChange={event=>setKeyword(event.target.value)} placeholder="搜索标题、摘要或正文"/>{(keyword||category||tag)&&<button onClick={clearFilters}>清除筛选</button>}</label>{loading&&<div className="ryu-state">正在读取文章...</div>}{error&&<div className="ryu-state error">{error}</div>}{!loading&&!error&&!data.posts.length&&<div className="ryu-state">Rain7 还没有发布文章，前往内容管理写下第一篇吧。</div>}
<div className="ryu-post-list">{data.posts.map((post,index)=><a className="ryu-post-card" href={`/rain7/article?slug=${encodeURIComponent(post.slug)}`} key={post.id}><div className="ryu-post-copy"><h2>{post.title}</h2><div className="ryu-post-meta"><span><CalendarDays/>{new Date(post.publishedAt).toLocaleDateString("zh-CN")}</span><span>▣ 约 {readingTime(post)} 分钟</span><span><Eye/>{post.viewCount||0} 次</span></div><p>{post.summary||"打开文章，继续阅读完整内容。"}</p><footer>{post.category&&<b><FolderOpen/>{post.category}</b>}{splitTags(post.tags).slice(0,4).map(item=><i key={item}><Tag/>{item}</i>)}</footer></div><div className="ryu-post-cover" style={{backgroundImage:`url(${post.coverUrl||(index%2?"/rain7/home.webp":"/rain7/post-placeholder.webp")})`}}><span>→</span></div></a>)}</div></main></div></div>}