import { useEffect, useMemo, useState } from "react";
import { CalendarDays, Eye, Folder, Search, Tag } from "lucide-react";

type Summary={id:number;title:string;slug:string;summary:string|null;coverUrl:string|null;category:string|null;tags:string|null;pinned:boolean;viewCount:number;publishedAt:string};
type Archive={posts:Summary[];categories:string[];tags:string[]};
const api=(path:string)=>fetch(path).then(async response=>{const type=response.headers.get("content-type")||"";if(!type.includes("application/json"))throw new Error("文章服务暂不可用");const body=await response.json();if(!response.ok||body.code&&body.code!=="SUCCESS")throw new Error(body.message||"请求失败");return body.data;});
const splitTags=(value:string|null)=>value?.split(",").map(item=>item.trim()).filter(Boolean)||[];

export default function Rain7BlogApp(){const[data,setData]=useState<Archive>({posts:[],categories:[],tags:[]});const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[keyword,setKeyword]=useState("");const[category,setCategory]=useState("");const[tag,setTag]=useState("");
 const query=useMemo(()=>{const params=new URLSearchParams({site:"RAIN7"});if(keyword)params.set("keyword",keyword);if(category)params.set("category",category);if(tag)params.set("tag",tag);return params.toString()},[keyword,category,tag]);
 useEffect(()=>{setLoading(true);setError("");api(`/api/public/blog/posts?${query}`).then(setData).catch(e=>setError(e.message)).finally(()=>setLoading(false));},[query]);
 return <div className="rain-grid"><main><div className="rain-shortcuts"><button onClick={()=>{setKeyword("");setCategory("");setTag("")}}><Folder/><span><b>全部文章</b><small>浏览所有 Rain7 内容</small></span></button><a href="#rain-search"><Search/><span><b>搜索</b><small>快速定位文章</small></span></a><button onClick={()=>document.getElementById("rain-categories")?.scrollIntoView({behavior:"smooth"})}><Tag/><span><b>分类与标签</b><small>按主题探索</small></span></button></div><div className="rain-section-title"><div><span>RECENT POSTS</span><h2>{category||tag||keyword?"筛选结果":"最近文章"}</h2></div><small>{data.posts.length} 篇公开文章</small></div>{loading&&<div className="rain-state">正在读取文章…</div>}{error&&<div className="rain-state error">{error}</div>}{!loading&&!error&&!data.posts.length&&<div className="rain-state">Rain7 还没有发布文章，请前往内容管理创建第一篇。</div>}<div className="rain-post-list">{data.posts.map(post=><a className="rain-post" href={`/rain7/article?slug=${encodeURIComponent(post.slug)}`} key={post.id}><div className="rain-post-copy"><div className="rain-meta"><span>{post.category||"随笔"}</span><time><CalendarDays/> {new Date(post.publishedAt).toLocaleDateString("zh-CN")}</time><small><Eye/> {post.viewCount}</small></div><h3>{post.title}</h3><p>{post.summary||"打开文章，继续阅读完整内容。"}</p><footer>{splitTags(post.tags).slice(0,4).map(item=><i key={item}># {item}</i>)}</footer></div><div className={`rain-cover ${post.coverUrl?"":"empty"}`} style={post.coverUrl?{backgroundImage:`url(${post.coverUrl})`}:undefined}>{!post.coverUrl&&<span>R7</span>}</div></a>)}</div></main><aside><section className="rain-profile"><img src="/rain7/rain7-avatar.svg"/><h3>Rain7</h3><p>热爱技术，也认真生活。<br/>记录每一次成长与抵达。</p><div><span><b>{data.posts.length}</b><small>文章</small></span><span><b>{data.categories.length}</b><small>分类</small></span><span><b>{data.tags.length}</b><small>标签</small></span></div></section><section className="rain-side" id="rain-search"><h4>搜索文章</h4><label><input value={keyword} onChange={e=>setKeyword(e.target.value)} placeholder="标题、摘要或正文…"/><Search/></label></section><section className="rain-side" id="rain-categories"><h4>分类</h4><button className={!category?"active":""} onClick={()=>setCategory("")}>全部文章</button>{data.categories.map(item=><button className={category===item?"active":""} key={item} onClick={()=>setCategory(item)}>{item}</button>)}</section><section className="rain-side"><h4>标签</h4><div className="rain-tags">{data.tags.map(item=><button className={tag===item?"active":""} key={item} onClick={()=>setTag(tag===item?"":item)}>{item}</button>)}</div></section></aside></div>}