import { useEffect, useState } from "react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import rehypeExternalLinks from "rehype-external-links";
import { CalendarDays, Eye } from "lucide-react";
type Post={title:string;summary:string|null;markdownContent:string;coverUrl:string|null;category:string|null;tags:string|null;viewCount:number;publishedAt:string|null;seoTitle:string|null;seoDescription:string|null};
const formatDate=(value:string)=>new Date(value).toLocaleDateString("zh-CN",{year:"numeric",month:"long",day:"numeric"});
const readingTime=(content:string)=>Math.max(1,Math.ceil(content.replace(/\s/g,"").length/450));
export default function Rain7ArticleApp(){const[post,setPost]=useState<Post|null>(null);const[error,setError]=useState("");useEffect(()=>{const slug=new URLSearchParams(location.search).get("slug");if(!slug){setError("缺少文章地址");return}fetch(`/api/public/blog/posts/${encodeURIComponent(slug)}?site=RAIN7`).then(async response=>{if(!(response.headers.get("content-type")||"").includes("application/json"))throw new Error("文章服务暂不可用");const body=await response.json();if(!response.ok||body.code&&body.code!=="SUCCESS")throw new Error(body.message||"文章加载失败");return body.data}).then(value=>{setPost(value);document.title=`${value.seoTitle||value.title} · Rain7`;document.querySelector('meta[name="description"]')?.setAttribute("content",value.seoDescription||value.summary||"")}).catch(e=>setError(e.message))},[]);if(error)return <div className="rain-state error">{error}<br/><a href="/rain7/">返回 Rain7</a></div>;if(!post)return <div className="rain-state">正在读取文章…</div>;const tags=post.tags?.split(",").map(item=>item.trim()).filter(Boolean)||[];return <article className="rain-article"><header className="rain-article-header"><a className="rain-back-link" href="/rain7/">← 返回 Rain7</a><div className="rain-meta"><span className="rain-category">{post.category||"随笔"}</span>{post.publishedAt&&<time><CalendarDays/> {formatDate(post.publishedAt)}</time>}<span><Eye/> {post.viewCount||0} 次阅读</span><span>约 {readingTime(post.markdownContent)} 分钟</span></div><h1>{post.title}</h1>{post.summary&&<p className="rain-summary">{post.summary}</p>}{tags.length>0&&<div className="rain-tags">{tags.map(item=><i key={item}># {item}</i>)}</div>}</header>{post.coverUrl&&<div className="rain-article-cover" style={{backgroundImage:`url(${post.coverUrl})`}}/>}<div className="rain-markdown"><ReactMarkdown remarkPlugins={[remarkGfm]} rehypePlugins={[[rehypeExternalLinks,{target:"_blank",rel:["noopener","noreferrer"]}]]}>{post.markdownContent||""}</ReactMarkdown></div><footer><span>RAIN7 · END</span><h3>感谢你读到这里。</h3><p>愿这篇记录，也能成为下一次出发的坐标。</p><a href="/rain7/">继续浏览文章 →</a></footer></article>}
