<template>
  <div class="trading-page">
    <div class="hero">
      <div><span class="eyebrow">TRADING JOURNAL</span><h2>交易复盘</h2><p>数据给出证据，规则给出参考，最终判断由你保留。</p></div>
      <div class="quick-links"><el-button @click="$router.push('/stocks')">自选股 / 资金流</el-button><el-button @click="$router.push('/reminders')">提醒</el-button><el-button @click="$router.push('/reports')">自动报告</el-button></div>
    </div>
    <el-tabs v-model="tab" class="review-tabs" @tab-change="loadTab">
      <el-tab-pane label="思考记录" name="notes">
        <div class="toolbar"><div><el-date-picker v-model="noteDateFilter" value-format="YYYY-MM-DD" placeholder="筛选日期" clearable/><el-select v-model="noteScopeFilter" placeholder="全部主题" clearable><el-option label="大盘" value="MARKET"/><el-option label="个股" value="STOCK"/></el-select></div><el-button type="primary" @click="newNote">记录今天的想法</el-button></div>
        <el-alert title="先记录，再接入行情" description="思考记录保存在当前浏览器，不依赖行情接口。等数据源稳定后，可再把指数、板块和个股快照附加到记录中。" type="info" :closable="false" show-icon/>
        <div v-if="filteredNotes.length" class="note-list"><el-card v-for="note in filteredNotes" :key="note.id" class="note-card"><template #header><div class="card-head"><div><el-tag size="small" :type="note.scope==='MARKET'?'success':'primary'">{{note.scope==='MARKET'?'大盘':'个股'}}</el-tag><b>{{note.title||'无标题记录'}}</b><small>{{note.tradeDate}}<span v-if="note.stockCode"> · {{note.stockName||note.stockCode}}</span></small></div><div><el-button link @click="editNote(note)">编辑</el-button><el-button link type="danger" @click="removeNote(note.id)">删除</el-button></div></div></template><p class="note-content">{{note.content}}</p><div v-if="note.tags" class="note-tags"><el-tag v-for="tag in note.tags.split(',').filter(Boolean)" :key="tag" size="small" effect="plain">{{tag}}</el-tag></div></el-card></div><el-empty v-else description="还没有思考记录，先写下今天的判断吧"/>
      </el-tab-pane>
      <el-tab-pane label="每日复盘" name="review">
        <div class="toolbar"><div><el-date-picker v-model="reviewForm.tradeDate" value-format="YYYY-MM-DD"/><el-select v-model="reviewForm.snapshotType"><el-option label="盘中快照" value="REALTIME"/><el-option label="收盘定稿" value="FINAL"/></el-select></div><div><el-button :loading="refreshing" @click="refresh">重试自动获取</el-button><el-button @click="generateTradingReport">生成研究报告</el-button><el-button type="primary" @click="reviewVisible=true">手工录入</el-button></div></div>
        <el-alert v-if="latestReview?.collectionStatus==='FAILED'" :title="latestReview.failureReason" description="旧数据已保留，可重试或继续手工填写。" type="error" :closable="false" show-icon/>
        <div v-if="latestReview" class="review-summary">
          <el-card><small>市场阶段</small><strong>{{latestReview.marketStage||'数据不完整'}}</strong><span>评分 {{latestReview.sentimentScore??'-'}}</span></el-card>
          <el-card><small>建议仓位</small><strong>{{latestReview.suggestedPosition==null?'-':latestReview.suggestedPosition+'%'}}</strong><span>{{latestReview.ruleVersion||'待计算'}}</span></el-card>
          <el-card><small>数据状态</small><strong>{{completeness(latestReview.dataCompleteness)}}</strong><span>{{latestReview.freshness||'手工数据'}}</span></el-card>
          <el-card><small>最后成功</small><strong class="small-value">{{formatTime(latestReview.lastSuccessAt)}}</strong><span>{{latestReview.dataSource||'MANUAL'}}</span></el-card>
        </div>
        <TradingReviewAnalytics v-if="latestReview" :trade-date="latestReview.tradeDate" :refresh-key="analyticsRefreshKey"/>
        <TradingMarketDetails v-if="latestReview" :review="latestReview"/>
        <el-card v-if="latestReview" class="conclusion"><template #header>自动结论（不会覆盖人工判断）</template><p>{{latestReview.autoConclusion}}</p><el-divider/><b>人工判断</b><p>{{latestReview.manualJudgment||'尚未填写'}}</p></el-card>
        <el-card><el-table :data="reviews"><el-table-column prop="tradeDate" label="交易日" width="120"/><el-table-column label="类型" width="105"><template #default="s">{{s.row.snapshotType==='FINAL'?'收盘':'盘中'}}</template></el-table-column><el-table-column prop="marketStage" label="阶段"/><el-table-column prop="sentimentScore" label="评分"/><el-table-column prop="risingCount" label="上涨"/><el-table-column prop="fallingCount" label="下跌"/><el-table-column label="状态"><template #default="s"><el-tag :type="s.row.dataCompleteness==='COMPLETE'?'success':'warning'">{{completeness(s.row.dataCompleteness)}}</el-tag></template></el-table-column><el-table-column label="操作" width="150"><template #default="s"><el-button link @click="editReview(s.row)">编辑</el-button><el-button link type="danger" @click="deleteReviewRow(s.row.id)">删除</el-button></template></el-table-column></el-table></el-card>
      </el-tab-pane>

      <el-tab-pane label="交易日志" name="trades">
        <div class="toolbar"><el-alert title="支持一笔交易多次买入和多次卖出，盈亏由成交明细计算。" type="info" :closable="false"/><el-button type="primary" @click="newTrade">新建交易</el-button></div>
        <div class="card-list"><el-card v-for="item in trades" :key="item.id" class="trade-card"><template #header><div class="card-head"><b>{{item.stockName}} <small>{{item.stockCode}}</small></b><el-tag :type="item.status==='CLOSED'?'info':'success'">{{item.status==='CLOSED'?'已平仓':'持仓中'}}</el-tag></div></template><p>{{item.strategy||'未填写策略'}}</p><div><el-button @click="openTrade(item)">成交与盈亏</el-button><el-button @click="editTrade(item)">编辑</el-button><el-button type="danger" plain @click="deleteTradeRow(item.id)">删除</el-button></div></el-card></div>
      </el-tab-pane>

      <el-tab-pane label="次日计划" name="plans">
        <div class="toolbar"><span>计划可关联提醒编号，并可跳转自动报告继续整理。</span><el-button type="primary" @click="newPlan">新建计划</el-button></div>
        <el-card><el-table :data="plans"><el-table-column prop="tradeDate" label="交易日"/><el-table-column prop="targetPosition" label="目标仓位"><template #default="s">{{s.row.targetPosition??'-'}}%</template></el-table-column><el-table-column prop="marketPremise" label="市场前提" show-overflow-tooltip/><el-table-column prop="watchStocks" label="关注标的" show-overflow-tooltip/><el-table-column label="状态"><template #default="s"><el-tag>{{planStatus(s.row.status)}}</el-tag></template></el-table-column><el-table-column label="操作" width="150"><template #default="s"><el-button link @click="editPlan(s.row)">编辑</el-button><el-button link type="danger" @click="deletePlanRow(s.row.id)">删除</el-button></template></el-table-column></el-table></el-card>
      </el-tab-pane>

      <el-tab-pane label="错题本" name="mistakes">
        <div class="toolbar"><span>重复出现的错误会按次数进入高频错误统计。</span><el-button type="primary" @click="newMistake">记录错误</el-button></div>
        <div class="card-list"><el-card v-for="item in mistakes" :key="item.id"><template #header><div class="card-head"><b>{{item.title}}</b><el-tag>{{item.category}} × {{item.repeatCount}}</el-tag></div></template><p>{{item.description}}</p><small>根因：{{item.rootCause||'-'}}　改进：{{item.correction||'-'}}</small><div class="actions"><el-button link @click="editMistake(item)">编辑</el-button><el-button link type="danger" @click="deleteMistakeRow(item.id)">删除</el-button></div></el-card></div>
      </el-tab-pane>

      <el-tab-pane label="统计看板" name="stats">
        <el-alert title="统计口径" description="胜率只统计已完全平仓交易；买入成本含佣金/印花税/过户费，卖出净额扣除全部费用；未实现盈亏按最新价与剩余加权成本计算；盈亏比=盈利交易平均已实现盈利÷亏损交易平均已实现亏损绝对值。" type="info" :closable="false" show-icon/>
        <div class="stats" v-if="stats"><el-card v-for="item in statCards" :key="item.label"><small>{{item.label}}</small><strong>{{item.value}}</strong></el-card></div>
        <el-card><template #header>高频错误</template><el-empty v-if="!stats?.frequentErrors.length" description="暂无错题统计"/><div v-for="item in stats?.frequentErrors" :key="item.category" class="error-row"><span>{{item.category}}</span><el-progress :percentage="errorPercent(item.count)" :format="()=>item.count+' 次'"/></div></el-card>
      </el-tab-pane>
    </el-tabs>

    <el-dialog v-model="reviewVisible" title="每日复盘" width="min(900px,96vw)" class="mobile-full-dialog" :close-on-click-modal="false"><el-form label-position="top"><div class="form-grid"><el-form-item label="交易日"><el-date-picker v-model="reviewForm.tradeDate" value-format="YYYY-MM-DD"/></el-form-item><el-form-item label="快照"><el-select v-model="reviewForm.snapshotType"><el-option label="盘中" value="REALTIME"/><el-option label="收盘" value="FINAL"/></el-select></el-form-item><el-form-item v-for="field in metricFields" :key="field.key" :label="field.label"><el-input-number v-model="reviewForm[field.key]" :precision="field.precision" controls-position="right"/></el-form-item></div><el-form-item label="行业/概念板块"><el-input v-model="reviewForm.sectors" type="textarea" :rows="3"/></el-form-item><el-form-item label="核心股"><el-input v-model="reviewForm.coreStocks" type="textarea"/></el-form-item><el-form-item label="持仓检查"><el-input v-model="reviewForm.holdingCheck" type="textarea"/></el-form-item><el-form-item label="人工判断"><el-input v-model="reviewForm.manualJudgment" type="textarea" :rows="3"/></el-form-item></el-form><template #footer><el-button @click="reviewVisible=false">取消</el-button><el-button type="primary" @click="submitReview">保存并计算</el-button></template></el-dialog>

    <el-dialog v-model="tradeVisible" title="交易日志" width="min(760px,96vw)" :close-on-click-modal="false"><el-form label-position="top"><div class="form-grid"><el-form-item label="股票代码"><el-input v-model="tradeForm.stockCode"/></el-form-item><el-form-item label="股票名称"><el-input v-model="tradeForm.stockName"/></el-form-item><el-form-item label="最新价"><el-input-number v-model="tradeForm.latestPrice" :precision="4"/></el-form-item><el-form-item label="按计划执行"><el-switch v-model="tradeForm.planned"/></el-form-item></div><el-form-item label="策略"><el-input v-model="tradeForm.strategy"/></el-form-item><el-form-item label="买入逻辑"><el-input v-model="tradeForm.buyLogic" type="textarea"/></el-form-item><el-form-item label="卖出逻辑"><el-input v-model="tradeForm.sellLogic" type="textarea"/></el-form-item><el-form-item label="三问：买入逻辑是否成立？"><el-input v-model="tradeForm.questionBuyLogic"/></el-form-item><el-form-item label="三问：封板资金是谁？"><el-input v-model="tradeForm.questionSealFunds"/></el-form-item><el-form-item label="三问：接盘资金是谁？"><el-input v-model="tradeForm.questionTakeoverFunds"/></el-form-item><el-form-item label="执行偏差 / 备注"><el-input v-model="tradeForm.planExecutionNote" type="textarea"/></el-form-item></el-form><template #footer><el-button @click="tradeVisible=false">取消</el-button><el-button type="primary" @click="submitTrade">保存</el-button></template></el-dialog>

    <el-drawer v-model="detailVisible" :title="tradeDetail?.trade.stockName+' · 成交明细'" size="min(720px,100%)"><div v-if="tradeDetail"><div class="metrics"><span>加权成本 <b>{{money(tradeDetail.metrics.averageCost)}}</b></span><span>剩余 <b>{{tradeDetail.metrics.remainingQuantity}}</b></span><span>已实现 <b>{{money(tradeDetail.metrics.realizedProfit)}}</b></span><span>未实现 <b>{{money(tradeDetail.metrics.unrealizedProfit)}}</b></span><span>总费用 <b>{{money(tradeDetail.metrics.totalFees)}}</b></span><span>收益率 <b>{{tradeDetail.metrics.returnRate}}%</b></span></div><el-table :data="tradeDetail.executions"><el-table-column label="方向" width="75"><template #default="s"><el-tag :type="s.row.side==='BUY'?'danger':'success'">{{s.row.side==='BUY'?'买入':'卖出'}}</el-tag></template></el-table-column><el-table-column prop="quantity" label="数量"/><el-table-column prop="price" label="价格"/><el-table-column prop="commission" label="佣金"/><el-table-column prop="stampDuty" label="印花税"/><el-table-column label="操作" width="70"><template #default="s"><el-button link type="danger" @click="deleteExecutionRow(s.row.id)">删除</el-button></template></el-table-column></el-table><el-divider/> <h4>新增一笔成交</h4><div class="execution-form"><el-select v-model="executionForm.side"><el-option label="买入" value="BUY"/><el-option label="卖出" value="SELL"/></el-select><el-input-number v-model="executionForm.quantity" :min="0.0001" placeholder="数量"/><el-input-number v-model="executionForm.price" :min="0.0001" :precision="4" placeholder="价格"/><el-date-picker v-model="executionForm.occurredAt" type="datetime" value-format="YYYY-MM-DDTHH:mm:ss"/><el-input-number v-model="executionForm.commission" :min="0" :precision="4" placeholder="佣金"/><el-input-number v-model="executionForm.stampDuty" :min="0" :precision="4" placeholder="印花税"/><el-input-number v-model="executionForm.transferFee" :min="0" :precision="4" placeholder="过户费"/><el-button type="primary" @click="submitExecution">添加成交</el-button></div></div></el-drawer>

    <el-dialog v-model="planVisible" title="次日计划" width="min(720px,96vw)" :close-on-click-modal="false"><el-form label-position="top"><div class="form-grid"><el-form-item label="交易日"><el-date-picker v-model="planForm.tradeDate" value-format="YYYY-MM-DD"/></el-form-item><el-form-item label="目标仓位 %"><el-input-number v-model="planForm.targetPosition" :min="0" :max="100"/></el-form-item><el-form-item label="执行状态"><el-select v-model="planForm.status"><el-option label="草稿" value="DRAFT"/><el-option label="执行中" value="ACTIVE"/><el-option label="已完成" value="COMPLETED"/><el-option label="已取消" value="CANCELLED"/></el-select></el-form-item></div><el-form-item label="市场前提"><el-input v-model="planForm.marketPremise" type="textarea"/></el-form-item><el-form-item label="关注标的"><el-input v-model="planForm.watchStocks" type="textarea"/></el-form-item><el-form-item label="计划交易"><el-input v-model="planForm.plannedTrades" type="textarea"/></el-form-item><el-form-item label="风险控制"><el-input v-model="planForm.riskControls" type="textarea"/></el-form-item><el-form-item label="关联提醒 ID"><el-input v-model="planForm.reminderIds" placeholder="例如 12,15"/></el-form-item><el-form-item label="报告备注"><el-input v-model="planForm.reportNote"/></el-form-item></el-form><template #footer><el-button @click="planVisible=false">取消</el-button><el-button type="primary" @click="submitPlan">保存</el-button></template></el-dialog>

    <el-dialog v-model="mistakeVisible" title="错题记录" width="min(680px,96vw)" :close-on-click-modal="false"><el-form label-position="top"><div class="form-grid"><el-form-item label="日期"><el-date-picker v-model="mistakeForm.occurredDate" value-format="YYYY-MM-DD"/></el-form-item><el-form-item label="分类"><el-input v-model="mistakeForm.category" placeholder="追高 / 计划外交易 / 止损拖延"/></el-form-item><el-form-item label="标题"><el-input v-model="mistakeForm.title"/></el-form-item><el-form-item label="重复次数"><el-input-number v-model="mistakeForm.repeatCount" :min="1"/></el-form-item></div><el-form-item label="错误描述"><el-input v-model="mistakeForm.description" type="textarea"/></el-form-item><el-form-item label="根因"><el-input v-model="mistakeForm.rootCause" type="textarea"/></el-form-item><el-form-item label="改进动作"><el-input v-model="mistakeForm.correction" type="textarea"/></el-form-item></el-form><template #footer><el-button @click="mistakeVisible=false">取消</el-button><el-button type="primary" @click="submitMistake">保存</el-button></template></el-dialog>
    <el-dialog v-model="noteVisible" title="记录交易思考" width="min(720px,96vw)" :close-on-click-modal="false"><el-form label-position="top"><div class="form-grid"><el-form-item label="日期"><el-date-picker v-model="noteForm.tradeDate" value-format="YYYY-MM-DD"/></el-form-item><el-form-item label="主题"><el-select v-model="noteForm.scope"><el-option label="大盘" value="MARKET"/><el-option label="个股" value="STOCK"/></el-select></el-form-item><el-form-item label="股票代码（可选）"><el-input v-model="noteForm.stockCode" placeholder="例如 600519"/></el-form-item><el-form-item label="股票名称（可选）"><el-input v-model="noteForm.stockName"/></el-form-item></div><el-form-item label="标题"><el-input v-model="noteForm.title" placeholder="一句话概括今天的判断"/></el-form-item><el-form-item label="思考内容"><el-input v-model="noteForm.content" type="textarea" :rows="9" maxlength="5000" show-word-limit placeholder="记录事实、判断、依据、风险和明天要验证的信号……"/></el-form-item><el-form-item label="标签"><el-input v-model="noteForm.tags" placeholder="例如 情绪周期,观察,不追高（用逗号分隔）"/></el-form-item></el-form><template #footer><el-button @click="noteVisible=false">取消</el-button><el-button type="primary" @click="saveNote">保存记录</el-button></template></el-dialog>
  </div>
</template>

<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, reactive, ref, watch } from 'vue';
import { ElMessage, ElMessageBox } from 'element-plus';
import * as api from '@/api/tradingReview';
import { generateReport } from '@/api/productivity';
import type { DailyReview, NextPlan, TradeLog, TradingMistake, TradingAlertRule, TradingAlertEvent, TradingMarketAlertRule, TradingMarketAlertEvent } from '@/api/tradingReview';
import TradingMarketDetails from './TradingMarketDetails.vue';
import TradingReviewAnalytics from './TradingReviewAnalytics.vue';

const today=()=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Shanghai'}).format(new Date());
const now=()=>new Date().toISOString().slice(0,19);
const tab=ref('review'),reviews=ref<DailyReview[]>([]),trades=ref<TradeLog[]>([]),plans=ref<NextPlan[]>([]),alertRules=ref<TradingAlertRule[]>([]),alertEvents=ref<TradingAlertEvent[]>([]),marketAlertRules=ref<TradingMarketAlertRule[]>([]),marketAlertEvents=ref<TradingMarketAlertEvent[]>([]),mistakes=ref<TradingMistake[]>([]),stats=ref<api.TradingStats>();
const analyticsRefreshKey=ref(0);
type ThoughtNote={id:string;tradeDate:string;scope:'MARKET'|'STOCK';stockCode:string;stockName:string;title:string;content:string;tags:string;updatedAt:string};
const notes=ref<ThoughtNote[]>([]),noteVisible=ref(false),noteDateFilter=ref(''),noteScopeFilter=ref(''),editingNoteId=ref<string>();
const noteForm=reactive<ThoughtNote>({id:'',tradeDate:today(),scope:'MARKET',stockCode:'',stockName:'',title:'',content:'',tags:'',updatedAt:''});
const filteredNotes=computed(()=>notes.value.filter(note=>(!noteDateFilter.value||note.tradeDate===noteDateFilter.value)&&(!noteScopeFilter.value||note.scope===noteScopeFilter.value)).sort((a,b)=>b.tradeDate.localeCompare(a.tradeDate)||b.updatedAt.localeCompare(a.updatedAt)));
const refreshing=ref(false),alertScanning=ref(false),marketAlertScanning=ref(false),reviewVisible=ref(false),tradeVisible=ref(false),detailVisible=ref(false),planVisible=ref(false),alertVisible=ref(false),marketAlertVisible=ref(false),mistakeVisible=ref(false),editingId=ref<number>(),tradeDetail=ref<api.TradeDetail>();
const reviewForm=reactive<any>({tradeDate:today(),snapshotType:'FINAL',tradingDay:true,status:'DRAFT',shanghaiChange:null,shenzhenChange:null,chinextChange:null,risingCount:null,fallingCount:null,flatCount:null,limitUpCount:null,limitDownCount:null,brokenBoardCount:null,brokenBoardRate:null,maxStreak:null,turnoverAmount:null,turnoverChange:null,sectors:'',coreStocks:'',holdingCheck:'',manualJudgment:''});
const blankTrade=()=>({stockCode:'',stockName:'',status:'OPEN',strategy:'',buyLogic:'',sellLogic:'',planned:false,planExecutionNote:'',questionBuyLogic:'',questionSealFunds:'',questionTakeoverFunds:'',latestPrice:null,sourceAlertEventId:null,sourceMarketAlertEventId:null,signalType:'',signalReason:'',notes:''});
const tradeForm=reactive<any>(blankTrade());
const executionForm=reactive<any>({side:'BUY',quantity:100,price:null,commission:0,stampDuty:0,transferFee:0,occurredAt:now(),remark:''});
const planForm=reactive<any>({tradeDate:today(),marketPremise:'',targetPosition:0,watchStocks:'',plannedTrades:'',riskControls:'',reminderIds:'',reportNote:'',status:'DRAFT'});
const mistakeForm=reactive<any>({occurredDate:today(),category:'',title:'',description:'',rootCause:'',correction:'',status:'OPEN',repeatCount:1});
const alertForm=reactive<any>({watchItemId:null,planId:null,stockCode:'',stockName:'',ruleType:'PRICE',direction:'ABOVE',thresholdValue:null,referencePosition:null,title:'',note:'',enabled:true,onceOnly:true,validFrom:'',validTo:''});
const marketAlertForm=reactive<any>({ruleType:'MARKET_METRIC',snapshotType:'ANY',metricKey:'BROKEN_BOARD_RATE',direction:'ABOVE',thresholdValue:null,sectorName:'',sectorLevel:null,title:'',note:'',enabled:true,onceOnly:false,validFrom:'',validTo:''});
const metricFields=[{key:'shanghaiChange',label:'上证涨跌 %',precision:2},{key:'shenzhenChange',label:'深证涨跌 %',precision:2},{key:'chinextChange',label:'创业板涨跌 %',precision:2},{key:'risingCount',label:'上涨家数',precision:0},{key:'fallingCount',label:'下跌家数',precision:0},{key:'flatCount',label:'平盘家数',precision:0},{key:'limitUpCount',label:'涨停数',precision:0},{key:'limitDownCount',label:'跌停数',precision:0},{key:'brokenBoardCount',label:'炸板数',precision:0},{key:'brokenBoardRate',label:'炸板率 %',precision:2},{key:'maxStreak',label:'连板高度',precision:0},{key:'turnoverAmount',label:'成交额（元）',precision:2},{key:'turnoverChange',label:'成交额变化 %',precision:2}] as const;
const latestReview=computed(()=>reviews.value[0]);
const statCards=computed(()=>stats.value?[{label:'已平仓',value:stats.value.closedTrades},{label:'胜率',value:stats.value.winRate+'%'},{label:'平均收益',value:stats.value.averageReturn+'%'},{label:'盈亏比',value:stats.value.profitLossRatio},{label:'已实现盈亏',value:money(stats.value.realizedProfit)},{label:'未实现盈亏',value:money(stats.value.unrealizedProfit)},{label:'总费用',value:money(stats.value.totalFees)}]:[]);

async function loadAlerts(){alertRules.value=(await api.listAlertRules()).data;alertEvents.value=(await api.listAlertEvents()).data;marketAlertRules.value=(await api.listMarketAlertRules()).data;marketAlertEvents.value=(await api.listMarketAlertEvents()).data;}
async function loadTab(){if(tab.value==='review')reviews.value=(await api.listReviews()).data;if(tab.value==='trades'){trades.value=(await api.listTrades()).data;await loadAlerts();}if(tab.value==='plans')plans.value=(await api.listPlans()).data;if(tab.value==='alerts')await loadAlerts();if(tab.value==='mistakes')mistakes.value=(await api.listMistakes()).data;if(tab.value==='stats')stats.value=(await api.getTradingStats()).data;}
function persistNotes(){localStorage.setItem('trading-thought-notes',JSON.stringify(notes.value));}
function newNote(){editingNoteId.value=undefined;Object.assign(noteForm,{id:'',tradeDate:today(),scope:'MARKET',stockCode:'',stockName:'',title:'',content:'',tags:'',updatedAt:''});noteVisible.value=true;}
function editNote(note:ThoughtNote){editingNoteId.value=note.id;Object.assign(noteForm,note);noteVisible.value=true;}
function saveNote(){if(!noteForm.content.trim()){ElMessage.warning('请先写下思考内容');return;}const item={...noteForm,id:editingNoteId.value||crypto.randomUUID(),updatedAt:new Date().toISOString()};const index=notes.value.findIndex(note=>note.id===item.id);if(index>=0)notes.value.splice(index,1,item);else notes.value.unshift(item);persistNotes();noteVisible.value=false;ElMessage.success('思考记录已保存');}
async function removeNote(id:string){await confirmDelete();notes.value=notes.value.filter(note=>note.id!==id);persistNotes();}
async function refresh(){refreshing.value=true;try{const result=(await api.refreshMarket(reviewForm.tradeDate,reviewForm.snapshotType)).data;ElMessage[result.fresh?'success':'warning'](result.message);await loadTab();analyticsRefreshKey.value++;}finally{refreshing.value=false;}}
async function generateTradingReport(){const reference=latestReview.value?.tradeDate||reviewForm.tradeDate;const report=(await generateReport('TRADING_DAILY',reference)).data;ElMessage.success('交易研究日报已生成：'+report.title);}
function editReview(item:DailyReview){editingId.value=item.id;Object.assign(reviewForm,item);reviewVisible.value=true;}async function submitReview(){await api.saveReview(reviewForm,editingId.value);finish(reviewVisible);await loadTab();}async function deleteReviewRow(id:number){await confirmDelete();await api.removeReview(id);await loadTab();}
function newTrade(){editingId.value=undefined;Object.assign(tradeForm,blankTrade());tradeVisible.value=true;void loadAlerts();}function editTrade(item:TradeLog){editingId.value=item.id;Object.assign(tradeForm,blankTrade(),item);tradeVisible.value=true;void loadAlerts();}async function submitTrade(){await api.saveTrade(tradeForm,editingId.value);finish(tradeVisible);await loadTab();}async function deleteTradeRow(id:number){await confirmDelete();await api.removeTrade(id);await loadTab();}async function openTrade(item:TradeLog){tradeDetail.value=(await api.getTrade(item.id)).data;detailVisible.value=true;}async function submitExecution(){if(!tradeDetail.value)return;await api.addExecution(tradeDetail.value.trade.id,executionForm);tradeDetail.value=(await api.getTrade(tradeDetail.value.trade.id)).data;await loadTab();}async function deleteExecutionRow(id:number){if(!tradeDetail.value)return;await confirmDelete();await api.removeExecution(tradeDetail.value.trade.id,id);tradeDetail.value=(await api.getTrade(tradeDetail.value.trade.id)).data;await loadTab();}
function newPlan(){editingId.value=undefined;Object.assign(planForm,{tradeDate:today(),marketPremise:'',targetPosition:0,watchStocks:'',plannedTrades:'',riskControls:'',reminderIds:'',reportNote:'',status:'DRAFT'});planVisible.value=true;}function editPlan(item:NextPlan){editingId.value=item.id;Object.assign(planForm,item);planVisible.value=true;}async function submitPlan(){await api.savePlan(planForm,editingId.value);finish(planVisible);await loadTab();}async function deletePlanRow(id:number){await confirmDelete();await api.removePlan(id);await loadTab();}
function newAlertRule(){editingId.value=undefined;Object.assign(alertForm,{watchItemId:null,planId:null,stockCode:'',stockName:'',ruleType:'PRICE',direction:'ABOVE',thresholdValue:null,referencePosition:null,title:'',note:'',enabled:true,onceOnly:true,validFrom:'',validTo:''});alertVisible.value=true;}
function editAlertRule(item:TradingAlertRule){editingId.value=item.id;Object.assign(alertForm,item);alertVisible.value=true;}
async function submitAlertRule(){await api.saveAlertRule(alertForm,editingId.value);finish(alertVisible);await loadTab();}
async function toggleAlert(item:TradingAlertRule){await api.toggleAlertRule(item.id,item.enabled);await loadTab();}
async function deleteAlertRuleRow(id:number){await confirmDelete();await api.removeAlertRule(id);await loadTab();}
async function scanAlerts(){alertScanning.value=true;try{const result=(await api.scanAlertRules()).data;ElMessage.success(`扫描 ${result.checkedRules} 条，触发 ${result.triggeredEvents} 条，跳过 ${result.skippedRules} 条`);await loadTab();}finally{alertScanning.value=false;}}
function newMarketAlertRule(){editingId.value=undefined;Object.assign(marketAlertForm,{ruleType:'MARKET_METRIC',snapshotType:'ANY',metricKey:'BROKEN_BOARD_RATE',direction:'ABOVE',thresholdValue:null,sectorName:'',sectorLevel:null,title:'',note:'',enabled:true,onceOnly:false,validFrom:'',validTo:''});marketAlertVisible.value=true;}
function editMarketAlertRule(item:TradingMarketAlertRule){editingId.value=item.id;Object.assign(marketAlertForm,item);marketAlertVisible.value=true;}
async function submitMarketAlertRule(){await api.saveMarketAlertRule(marketAlertForm,editingId.value);finish(marketAlertVisible);await loadTab();}
async function toggleMarketAlert(item:TradingMarketAlertRule){await api.toggleMarketAlertRule(item.id,item.enabled);await loadTab();}
async function deleteMarketAlertRuleRow(id:number){await confirmDelete();await api.removeMarketAlertRule(id);await loadTab();}
async function scanMarketAlerts(){marketAlertScanning.value=true;try{const result=(await api.scanMarketAlertRules()).data;ElMessage.success(`市场扫描 ${result.checkedRules} 条，触发 ${result.triggeredEvents} 条，跳过 ${result.skippedRules} 条`);await loadTab();}finally{marketAlertScanning.value=false;}}
function newMistake(){editingId.value=undefined;Object.assign(mistakeForm,{occurredDate:today(),category:'',title:'',description:'',rootCause:'',correction:'',status:'OPEN',repeatCount:1});mistakeVisible.value=true;}function editMistake(item:TradingMistake){editingId.value=item.id;Object.assign(mistakeForm,item);mistakeVisible.value=true;}async function submitMistake(){await api.saveMistake(mistakeForm,editingId.value);finish(mistakeVisible);await loadTab();}async function deleteMistakeRow(id:number){await confirmDelete();await api.removeMistake(id);await loadTab();}
function finish(visible:{value:boolean}){visible.value=false;editingId.value=undefined;localStorage.removeItem('trading-review-draft');ElMessage.success('保存成功');}
const confirmDelete=()=>ElMessageBox.confirm('删除后不可恢复，是否继续？','确认删除',{type:'warning'});
const planStatus=(v:string)=>({DRAFT:'草稿',ACTIVE:'执行中',COMPLETED:'已完成',CANCELLED:'已取消'}[v]||v);
const alertRuleType=(v:string)=>({PRICE:'价格',CHANGE_PERCENT:'涨跌幅',STOP_LOSS:'止损',TAKE_PROFIT:'止盈',POSITION_DEVIATION:'仓位偏差'}[v]||v);
const alertDirection=(v:string)=>v==='BELOW'?'≤':'≥';
const alertStatus=(v:string)=>({MONITORING:'监控中',TRIGGERED:'已触发',DISABLED:'已停用',NO_QUOTE:'缺行情'}[v]||v);
const alertStatusType=(v:string)=>v==='TRIGGERED'?'danger':v==='NO_QUOTE'?'warning':v==='DISABLED'?'info':'success';
const notificationStatus=(v:string)=>({SENT:'已发送',NO_CHANNEL:'无通道',FAILED:'发送失败'}[v]||v);
const marketRuleType=(v:string)=>v==='SECTOR_METRIC'?'板块':'市场';
const marketMetricName=(v:string)=>({SENTIMENT_SCORE:'情绪评分',BROKEN_BOARD_RATE:'炸板率',LIMIT_DOWN_COUNT:'跌停数',LIMIT_UP_COUNT:'涨停数',RISING_COUNT:'上涨家数',FALLING_COUNT:'下跌家数',TURNOVER_CHANGE:'成交额变化',MAX_STREAK:'连板高度',MARKET_MEDIAN_CHANGE:'市场涨幅中位数',CHANGE:'板块涨跌幅',TURNOVER:'板块成交额',RISING:'板块上涨家数',FALLING:'板块下跌家数'}[v]||v);
const marketAlertRuleText=(row:TradingMarketAlertRule)=>marketRuleType(row.ruleType)+' '+(row.sectorName||'')+' '+marketMetricName(row.metricKey)+' '+alertDirection(row.direction)+' '+row.thresholdValue+(['BROKEN_BOARD_RATE','TURNOVER_CHANGE','MARKET_MEDIAN_CHANGE','CHANGE'].includes(row.metricKey)?'%':'');
const marketAlertEventText=(row:TradingMarketAlertEvent)=>row.tradeDate+' '+row.snapshotType+' '+(row.sectorName||'市场')+' '+marketMetricName(row.metricKey)+' 观察值 '+row.observedValue+'，阈值 '+row.thresholdValue;
const marketMetricOptions=[{label:'情绪评分',value:'SENTIMENT_SCORE'},{label:'炸板率',value:'BROKEN_BOARD_RATE'},{label:'跌停数',value:'LIMIT_DOWN_COUNT'},{label:'涨停数',value:'LIMIT_UP_COUNT'},{label:'上涨家数',value:'RISING_COUNT'},{label:'下跌家数',value:'FALLING_COUNT'},{label:'成交额变化',value:'TURNOVER_CHANGE'},{label:'连板高度',value:'MAX_STREAK'},{label:'市场涨幅中位数',value:'MARKET_MEDIAN_CHANGE'},{label:'板块涨跌幅',value:'CHANGE'},{label:'板块成交额',value:'TURNOVER'},{label:'板块涨停数',value:'LIMIT_UP_COUNT'},{label:'板块上涨家数',value:'RISING'},{label:'板块下跌家数',value:'FALLING'}];
const alertRuleText=(row:TradingAlertRule)=>`${alertRuleType(row.ruleType)} ${alertDirection(row.direction)} ${row.thresholdValue}${row.ruleType==='CHANGE_PERCENT'||row.ruleType==='POSITION_DEVIATION'?'%':''}`;
const alertEventText=(row:TradingAlertEvent)=>`${row.stockName} 观察值 ${row.observedValue}，阈值 ${row.thresholdValue}，最新价 ${row.latestPrice??'-'}，涨跌幅 ${row.changePercent??'-'}%`;
const money=(v?:number)=>Number(v||0).toFixed(2);const percent=(v?:number)=>Number(v||0).toFixed(2)+'%';const completeness=(v:string)=>({COMPLETE:'完整',INCOMPLETE:'数据不完整',MANUAL:'手工录入'}[v]||v);const formatTime=(v?:string)=>v?new Date(v).toLocaleString('zh-CN',{hour12:false}):'-';const errorPercent=(count:number)=>Math.min(100,count/Math.max(...(stats.value?.frequentErrors.map(v=>v.count)||[1]))*100);
const dirty=computed(()=>reviewVisible.value||tradeVisible.value||planVisible.value||alertVisible.value||marketAlertVisible.value||mistakeVisible.value||noteVisible.value);
watch([reviewForm,tradeForm,planForm,alertForm,marketAlertForm,mistakeForm],()=>{if(dirty.value)localStorage.setItem('trading-review-draft',JSON.stringify({reviewForm,tradeForm,planForm,alertForm,marketAlertForm,mistakeForm}));},{deep:true});
function beforeUnload(event:BeforeUnloadEvent){if(dirty.value){event.preventDefault();event.returnValue='';}}
onMounted(async()=>{window.addEventListener('beforeunload',beforeUnload);try{notes.value=JSON.parse(localStorage.getItem('trading-thought-notes')||'[]');}catch{notes.value=[];}const draft=localStorage.getItem('trading-review-draft');if(draft){try{const saved=JSON.parse(draft);Object.assign(reviewForm,saved.reviewForm||{});Object.assign(tradeForm,saved.tradeForm||{});Object.assign(planForm,saved.planForm||{});Object.assign(alertForm,saved.alertForm||{});Object.assign(marketAlertForm,saved.marketAlertForm||{});Object.assign(mistakeForm,saved.mistakeForm||{});ElMessage.info('已恢复上次未保存草稿');}catch{localStorage.removeItem('trading-review-draft');}}await loadTab();});onBeforeUnmount(()=>window.removeEventListener('beforeunload',beforeUnload));
</script>

<style scoped>
.trading-page{display:flex;flex-direction:column;gap:16px}.hero{display:flex;justify-content:space-between;align-items:flex-end;padding:24px;border-radius:20px;color:#fff;background:linear-gradient(135deg,#0f172a,#1e3a5f 55%,#0f766e)}.hero h2{margin:4px 0;font-size:30px}.hero p{margin:0;color:#cbd5e1}.eyebrow{font-size:11px;letter-spacing:.2em;color:#5eead4}.quick-links{display:flex;gap:8px}.toolbar{display:flex;justify-content:space-between;align-items:center;gap:12px;margin-bottom:14px}.toolbar>div{display:flex;gap:8px}.review-summary,.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:14px 0}.review-summary small,.review-summary strong,.review-summary span,.stats small,.stats strong{display:block}.review-summary strong,.stats strong{font-size:24px;margin:8px 0;color:#0f172a}.review-summary span,.review-summary small,.stats small{color:#64748b}.small-value{font-size:16px!important}.conclusion{margin-bottom:14px}.alert-card{margin-bottom:14px}.muted{color:#64748b}.alert-event{display:flex;flex-wrap:wrap;align-items:center;gap:8px}.alert-event span{color:#475569}.card-list{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.card-head{display:flex;justify-content:space-between;align-items:center}.card-head small{color:#64748b}.actions{margin-top:12px}.metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-bottom:16px}.metrics span{padding:12px;border-radius:12px;background:#f1f5f9}.metrics b{display:block;margin-top:4px}.execution-form{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}.form-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:0 16px}.form-grid :deep(.el-input-number),.form-grid :deep(.el-date-editor),.form-grid :deep(.el-select){width:100%}.error-row{display:grid;grid-template-columns:140px 1fr;align-items:center;gap:12px;margin:12px 0}
@media(max-width:900px){.card-list{grid-template-columns:repeat(2,1fr)}.review-summary,.stats{grid-template-columns:repeat(2,1fr)}}
@media(max-width:600px){.hero{align-items:flex-start;flex-direction:column;gap:16px;padding:18px}.quick-links{width:100%;overflow-x:auto}.toolbar{align-items:stretch;flex-direction:column}.toolbar>div{display:grid;grid-template-columns:1fr 1fr}.card-list,.form-grid,.execution-form{grid-template-columns:1fr}.review-summary,.stats{grid-template-columns:repeat(2,1fr);gap:8px}.review-summary :deep(.el-card__body),.stats :deep(.el-card__body){padding:13px}.review-summary strong,.stats strong{font-size:19px}.metrics{grid-template-columns:repeat(2,1fr)}.error-row{grid-template-columns:90px 1fr}.trading-page :deep(.el-table){min-width:680px}.trading-page :deep(.el-card){overflow-x:auto}}
</style>

